/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

static GnomeUIInfo file1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Print S_etup..."),
    NULL,
    (gpointer) on_choosePrinter1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_EXIT_ITEM (on_quit1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo edit1_uiinfo[] =
{
  GNOMEUIINFO_END
};

static GnomeUIInfo contact1_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_NEW_ITEM (N_("_New"), NULL, on_new1_activate, NULL),
  GNOMEUIINFO_MENU_EDIT_TREE (edit1_uiinfo),
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_SAVE_ITEM (on_save1_activate, NULL),
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_PRINT_ITEM (on_print1_activate, NULL),
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_CLEAR_ITEM (on_delete1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo menubar1_uiinfo[] =
{
  {
    GNOME_APP_UI_SUBTREE, N_("_File"),
    NULL,
    file1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Contact"),
    NULL,
    contact1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

GtkWidget*
create_ContactMainwindow (void)
{
  GtkWidget *ContactMainwindow;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *tbNew;
  GtkWidget *tbEdit;
  GtkWidget *tbSave;
  GtkWidget *hbox1;
  GtkWidget *lFindNumber;
  GtkWidget *eFindName;
  GtkWidget *lFindDesignation;
  GtkWidget *eFindCity;
  GtkWidget *bSearch;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *tree1;
  GtkWidget *notebook1;
  GtkWidget *vbox2;
  GtkWidget *table1;
  GtkWidget *calendar1;
  GtkWidget *table2;
  GtkWidget *cbTime;
  GtkWidget *eDate;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label25;
  GtkWidget *cbePriority;
  GtkWidget *label26;
  GtkWidget *cbeStatus;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *vbox4;
  GtkWidget *rbDay0;
  GSList *rbDay0_group = NULL;
  GtkWidget *rbDay1;
  GtkWidget *rbDay2;
  GtkWidget *rbDay3;
  GtkWidget *rbDay4;
  GtkWidget *rbDay5;
  GtkWidget *rbDay6;
  GtkWidget *rbDay7;
  GtkWidget *vbox6;
  GtkWidget *rbHour0;
  GSList *rbHour0_group = NULL;
  GtkWidget *rbHour1;
  GtkWidget *rbHour2;
  GtkWidget *rbHour3;
  GtkWidget *rbHour4;
  GtkWidget *rbHours5;
  GtkWidget *rbHour6;
  GtkWidget *rbHour7;
  GtkWidget *vbox7;
  GtkWidget *rbMinute00;
  GSList *rbMinute00_group = NULL;
  GtkWidget *rbMinute02;
  GtkWidget *rbMinute05;
  GtkWidget *rbMinute10;
  GtkWidget *rbMinute15;
  GtkWidget *rbMinute20;
  GtkWidget *rbMinute30;
  GtkWidget *rbMinute40;
  GtkWidget *rbMinute45;
  GtkWidget *rbMinute50;
  GtkWidget *hbox3;
  GtkWidget *label20;
  GtkWidget *label27;
  GtkWidget *eAlarmDay;
  GtkWidget *eAlarmHour;
  GtkWidget *eAlarmMinutes;
  GtkWidget *label28;
  GtkWidget *scrolledwindow2;
  GtkWidget *tvNotes;
  GtkWidget *hbox2;
  GtkWidget *vbox5;
  GtkWidget *label24;
  GtkWidget *scrolledwindow3;
  GtkWidget *tvAddress;
  GtkWidget *vbox8;
  GtkWidget *hbox4;
  GtkWidget *bCloseWindow;
  GtkWidget *bSleeping;
  GtkWidget *hbox5;
  GtkWidget *label29;
  GtkWidget *eSleepingTime;
  GtkWidget *label16;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  ContactMainwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ContactMainwindow), _("Contact"));

  vbox1 = gtk_vbox_new (FALSE, 17);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (ContactMainwindow), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);
  gnome_app_fill_menu (GTK_MENU_SHELL (menubar1), menubar1_uiinfo,
                       accel_group, FALSE, 0);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_ICONS);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  tmp_image = gtk_image_new_from_stock ("gtk-new", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  tbNew = (GtkWidget*) gtk_tool_button_new (tmp_image, "");
  gtk_widget_show (tbNew);
  gtk_container_add (GTK_CONTAINER (toolbar1), tbNew);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (tbNew), tooltips, _("create new contact"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-edit", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  tbEdit = (GtkWidget*) gtk_tool_button_new (tmp_image, "");
  gtk_widget_show (tbEdit);
  gtk_container_add (GTK_CONTAINER (toolbar1), tbEdit);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (tbEdit), tooltips, _("edit current contact"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-save", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  tbSave = (GtkWidget*) gtk_tool_button_new (tmp_image, "");
  gtk_widget_show (tbSave);
  gtk_container_add (GTK_CONTAINER (toolbar1), tbSave);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (tbSave), tooltips, _("save current contact"), NULL);

  hbox1 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, FALSE, 0);

  lFindNumber = gtk_label_new (_("Number"));
  gtk_widget_show (lFindNumber);
  gtk_box_pack_start (GTK_BOX (hbox1), lFindNumber, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (lFindNumber), GTK_JUSTIFY_CENTER);

  eFindName = gtk_entry_new ();
  gtk_widget_show (eFindName);
  gtk_box_pack_start (GTK_BOX (hbox1), eFindName, FALSE, FALSE, 0);

  lFindDesignation = gtk_label_new (_("Designation"));
  gtk_widget_show (lFindDesignation);
  gtk_box_pack_start (GTK_BOX (hbox1), lFindDesignation, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (lFindDesignation), GTK_JUSTIFY_CENTER);

  eFindCity = gtk_entry_new ();
  gtk_widget_show (eFindCity);
  gtk_box_pack_start (GTK_BOX (hbox1), eFindCity, FALSE, FALSE, 0);

  bSearch = gtk_button_new_with_mnemonic (_("Search"));
  gtk_widget_show (bSearch);
  gtk_box_pack_start (GTK_BOX (hbox1), bSearch, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow1, TRUE, TRUE, 0);
  gtk_widget_set_size_request (scrolledwindow1, -1, 166);
  GTK_WIDGET_UNSET_FLAGS (scrolledwindow1, GTK_CAN_FOCUS);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);

  tree1 = gtk_tree_view_new ();
  gtk_widget_show (tree1);
  gtk_container_add (GTK_CONTAINER (viewport1), tree1);
  GTK_WIDGET_UNSET_FLAGS (tree1, GTK_CAN_FOCUS);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox1), notebook1, TRUE, TRUE, 0);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox2);

  table1 = gtk_table_new (4, 5, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox2), table1, TRUE, TRUE, 0);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_table_attach (GTK_TABLE (table1), calendar1, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  table2 = gtk_table_new (7, 2, TRUE);
  gtk_widget_show (table2);
  gtk_table_attach (GTK_TABLE (table1), table2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  cbTime = gtk_combo_box_entry_new_text ();
  gtk_widget_show (cbTime);
  gtk_table_attach (GTK_TABLE (table2), cbTime, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("0:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("0:15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("0:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("0:45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("1:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("1:15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("1:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("1:45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("2:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("2:15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("2:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("2:45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("3:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("3:15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("3:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("3:45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("4:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("4:15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("4:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("4:45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("5:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("5:15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("5:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("5:45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("6:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("6:15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("6:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("6:45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("7:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("7:15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("7:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("7:45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("8:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("8:15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("8:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("8:45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("9:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("9:15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("9:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("9:45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("10:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("10:15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("10:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("10:45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("11:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("11:15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("11:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("11:45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("12:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("12:15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("12:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("12:45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("13:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("13:15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("13:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("13:45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("14:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("14:15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("14:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("14:45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("15:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("15:15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("15:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("15:45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("16:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("16:15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("16:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("16:45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("17:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("17:15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("17:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("17:45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("18:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("18:15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("18:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("18:45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("19:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("19:15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("19:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("19:45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("20:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("20:15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("20:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("20:45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("21:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("21:15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("21:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("21:45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("22:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("22:15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("22:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("22:45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("23:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("23:15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("23:30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbTime), _("23:45"));

  eDate = gtk_entry_new ();
  gtk_widget_show (eDate);
  gtk_table_attach (GTK_TABLE (table2), eDate, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (eDate), FALSE);

  label18 = gtk_label_new (_("Date"));
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (table2), label18, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0.5);

  label19 = gtk_label_new (_("Time"));
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (table2), label19, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0.5);

  label25 = gtk_label_new (_("Priority"));
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table2), label25, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  cbePriority = gtk_combo_box_entry_new_text ();
  gtk_widget_show (cbePriority);
  gtk_table_attach (GTK_TABLE (table2), cbePriority, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbePriority), _("Very Important"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbePriority), _("Important"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbePriority), _("Normal"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbePriority), _("Have a nice Day"));

  label26 = gtk_label_new (_("status"));
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table2), label26, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);

  cbeStatus = gtk_combo_box_entry_new_text ();
  gtk_widget_show (cbeStatus);
  gtk_table_attach (GTK_TABLE (table2), cbeStatus, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbeStatus), _("active"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbeStatus), _("ready"));

  label21 = gtk_label_new (_("Days"));
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (table1), label21, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label21), 0, 0.5);

  label22 = gtk_label_new (_("Hours"));
  gtk_widget_show (label22);
  gtk_table_attach (GTK_TABLE (table1), label22, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0.5);

  label23 = gtk_label_new (_("Minutes"));
  gtk_widget_show (label23);
  gtk_table_attach (GTK_TABLE (table1), label23, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_table_attach (GTK_TABLE (table1), vbox4, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  rbDay0 = gtk_radio_button_new_with_mnemonic (NULL, _("0 Day"));
  gtk_widget_show (rbDay0);
  gtk_box_pack_start (GTK_BOX (vbox4), rbDay0, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbDay0), rbDay0_group);
  rbDay0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbDay0));

  rbDay1 = gtk_radio_button_new_with_mnemonic (NULL, _("1 Day"));
  gtk_widget_show (rbDay1);
  gtk_box_pack_start (GTK_BOX (vbox4), rbDay1, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbDay1), rbDay0_group);
  rbDay0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbDay1));

  rbDay2 = gtk_radio_button_new_with_mnemonic (NULL, _("2 Days"));
  gtk_widget_show (rbDay2);
  gtk_box_pack_start (GTK_BOX (vbox4), rbDay2, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbDay2), rbDay0_group);
  rbDay0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbDay2));

  rbDay3 = gtk_radio_button_new_with_mnemonic (NULL, _("3 Days"));
  gtk_widget_show (rbDay3);
  gtk_box_pack_start (GTK_BOX (vbox4), rbDay3, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbDay3), rbDay0_group);
  rbDay0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbDay3));

  rbDay4 = gtk_radio_button_new_with_mnemonic (NULL, _("4 Days"));
  gtk_widget_show (rbDay4);
  gtk_box_pack_start (GTK_BOX (vbox4), rbDay4, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbDay4), rbDay0_group);
  rbDay0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbDay4));

  rbDay5 = gtk_radio_button_new_with_mnemonic (NULL, _("5 Days"));
  gtk_widget_show (rbDay5);
  gtk_box_pack_start (GTK_BOX (vbox4), rbDay5, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbDay5), rbDay0_group);
  rbDay0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbDay5));

  rbDay6 = gtk_radio_button_new_with_mnemonic (NULL, _("6 Days"));
  gtk_widget_show (rbDay6);
  gtk_box_pack_start (GTK_BOX (vbox4), rbDay6, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbDay6), rbDay0_group);
  rbDay0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbDay6));

  rbDay7 = gtk_radio_button_new_with_mnemonic (NULL, _("7 Days"));
  gtk_widget_show (rbDay7);
  gtk_box_pack_start (GTK_BOX (vbox4), rbDay7, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbDay7), rbDay0_group);
  rbDay0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbDay7));

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_table_attach (GTK_TABLE (table1), vbox6, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  rbHour0 = gtk_radio_button_new_with_mnemonic (NULL, _("0 Hour"));
  gtk_widget_show (rbHour0);
  gtk_box_pack_start (GTK_BOX (vbox6), rbHour0, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbHour0), rbHour0_group);
  rbHour0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbHour0));

  rbHour1 = gtk_radio_button_new_with_mnemonic (NULL, _("1 Hour"));
  gtk_widget_show (rbHour1);
  gtk_box_pack_start (GTK_BOX (vbox6), rbHour1, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbHour1), rbHour0_group);
  rbHour0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbHour1));

  rbHour2 = gtk_radio_button_new_with_mnemonic (NULL, _("2 Hours"));
  gtk_widget_show (rbHour2);
  gtk_box_pack_start (GTK_BOX (vbox6), rbHour2, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbHour2), rbHour0_group);
  rbHour0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbHour2));

  rbHour3 = gtk_radio_button_new_with_mnemonic (NULL, _("3 Hours"));
  gtk_widget_show (rbHour3);
  gtk_box_pack_start (GTK_BOX (vbox6), rbHour3, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbHour3), rbHour0_group);
  rbHour0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbHour3));

  rbHour4 = gtk_radio_button_new_with_mnemonic (NULL, _("4 Hours "));
  gtk_widget_show (rbHour4);
  gtk_box_pack_start (GTK_BOX (vbox6), rbHour4, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbHour4), rbHour0_group);
  rbHour0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbHour4));

  rbHours5 = gtk_radio_button_new_with_mnemonic (NULL, _("5 Hours"));
  gtk_widget_show (rbHours5);
  gtk_box_pack_start (GTK_BOX (vbox6), rbHours5, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbHours5), rbHour0_group);
  rbHour0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbHours5));

  rbHour6 = gtk_radio_button_new_with_mnemonic (NULL, _("6 Hours"));
  gtk_widget_show (rbHour6);
  gtk_box_pack_start (GTK_BOX (vbox6), rbHour6, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbHour6), rbHour0_group);
  rbHour0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbHour6));

  rbHour7 = gtk_radio_button_new_with_mnemonic (NULL, _("7 Hours"));
  gtk_widget_show (rbHour7);
  gtk_box_pack_start (GTK_BOX (vbox6), rbHour7, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbHour7), rbHour0_group);
  rbHour0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbHour7));

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_table_attach (GTK_TABLE (table1), vbox7, 4, 5, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  rbMinute00 = gtk_radio_button_new_with_mnemonic (NULL, _("0 Minutes"));
  gtk_widget_show (rbMinute00);
  gtk_box_pack_start (GTK_BOX (vbox7), rbMinute00, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbMinute00), rbMinute00_group);
  rbMinute00_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbMinute00));

  rbMinute02 = gtk_radio_button_new_with_mnemonic (NULL, _("2 Minutes"));
  gtk_widget_show (rbMinute02);
  gtk_box_pack_start (GTK_BOX (vbox7), rbMinute02, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbMinute02), rbMinute00_group);
  rbMinute00_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbMinute02));

  rbMinute05 = gtk_radio_button_new_with_mnemonic (NULL, _("5 Minutes"));
  gtk_widget_show (rbMinute05);
  gtk_box_pack_start (GTK_BOX (vbox7), rbMinute05, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbMinute05), rbMinute00_group);
  rbMinute00_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbMinute05));

  rbMinute10 = gtk_radio_button_new_with_mnemonic (NULL, _("10 Minutes"));
  gtk_widget_show (rbMinute10);
  gtk_box_pack_start (GTK_BOX (vbox7), rbMinute10, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbMinute10), rbMinute00_group);
  rbMinute00_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbMinute10));

  rbMinute15 = gtk_radio_button_new_with_mnemonic (NULL, _("15 Minutes"));
  gtk_widget_show (rbMinute15);
  gtk_box_pack_start (GTK_BOX (vbox7), rbMinute15, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbMinute15), rbMinute00_group);
  rbMinute00_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbMinute15));

  rbMinute20 = gtk_radio_button_new_with_mnemonic (NULL, _("20 Minutes"));
  gtk_widget_show (rbMinute20);
  gtk_box_pack_start (GTK_BOX (vbox7), rbMinute20, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbMinute20), rbMinute00_group);
  rbMinute00_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbMinute20));

  rbMinute30 = gtk_radio_button_new_with_mnemonic (NULL, _("30 Minutes"));
  gtk_widget_show (rbMinute30);
  gtk_box_pack_start (GTK_BOX (vbox7), rbMinute30, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbMinute30), rbMinute00_group);
  rbMinute00_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbMinute30));

  rbMinute40 = gtk_radio_button_new_with_mnemonic (NULL, _("40 Minutes"));
  gtk_widget_show (rbMinute40);
  gtk_box_pack_start (GTK_BOX (vbox7), rbMinute40, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbMinute40), rbMinute00_group);
  rbMinute00_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbMinute40));

  rbMinute45 = gtk_radio_button_new_with_mnemonic (NULL, _("45 Minutes"));
  gtk_widget_show (rbMinute45);
  gtk_box_pack_start (GTK_BOX (vbox7), rbMinute45, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbMinute45), rbMinute00_group);
  rbMinute00_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbMinute45));

  rbMinute50 = gtk_radio_button_new_with_mnemonic (NULL, _("50 Minutes"));
  gtk_widget_show (rbMinute50);
  gtk_box_pack_start (GTK_BOX (vbox7), rbMinute50, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbMinute50), rbMinute00_group);
  rbMinute00_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbMinute50));

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_table_attach (GTK_TABLE (table1), hbox3, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label20 = gtk_label_new (_("Alarm notify before: "));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox3), label20, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  label27 = gtk_label_new (_("D/H/M"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox3), label27, FALSE, FALSE, 0);

  eAlarmDay = gtk_entry_new ();
  gtk_widget_show (eAlarmDay);
  gtk_box_pack_start (GTK_BOX (hbox3), eAlarmDay, FALSE, TRUE, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (eAlarmDay), 3);

  eAlarmHour = gtk_entry_new ();
  gtk_widget_show (eAlarmHour);
  gtk_box_pack_start (GTK_BOX (hbox3), eAlarmHour, FALSE, TRUE, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (eAlarmHour), 2);

  eAlarmMinutes = gtk_entry_new ();
  gtk_widget_show (eAlarmMinutes);
  gtk_box_pack_start (GTK_BOX (hbox3), eAlarmMinutes, FALSE, TRUE, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (eAlarmMinutes), 2);

  label28 = gtk_label_new (_("Notice:"));
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (table1), label28, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label28), 0, 0.5);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox2), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_IN);

  tvNotes = gtk_text_view_new ();
  gtk_widget_show (tvNotes);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), tvNotes);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox2, TRUE, TRUE, 0);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (hbox2), vbox5, TRUE, TRUE, 0);

  label24 = gtk_label_new (_("Address"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (vbox5), label24, FALSE, FALSE, 0);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_box_pack_start (GTK_BOX (hbox2), scrolledwindow3, TRUE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_SHADOW_IN);

  tvAddress = gtk_text_view_new ();
  gtk_widget_show (tvAddress);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), tvAddress);
  gtk_widget_set_size_request (tvAddress, 254, 68);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox8);
  gtk_box_pack_start (GTK_BOX (hbox2), vbox8, TRUE, TRUE, 0);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox8), hbox4, TRUE, TRUE, 0);

  bCloseWindow = gtk_button_new_with_mnemonic (_("Close"));
  gtk_widget_show (bCloseWindow);
  gtk_box_pack_start (GTK_BOX (hbox4), bCloseWindow, FALSE, FALSE, 0);

  bSleeping = gtk_button_new_with_mnemonic (_("Sleeps"));
  gtk_widget_show (bSleeping);
  gtk_box_pack_start (GTK_BOX (hbox4), bSleeping, FALSE, FALSE, 0);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (hbox4), hbox5, FALSE, FALSE, 0);

  label29 = gtk_label_new (_("sleeps for Minutes"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox5), label29, FALSE, FALSE, 0);

  eSleepingTime = gtk_entry_new ();
  gtk_widget_show (eSleepingTime);
  gtk_box_pack_start (GTK_BOX (hbox5), eSleepingTime, TRUE, TRUE, 0);

  label16 = gtk_label_new (_("Contact"));
  gtk_widget_show (label16);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label16);

  g_signal_connect ((gpointer) tbNew, "clicked",
                    G_CALLBACK (on_new1_activate),
                    NULL);
  g_signal_connect ((gpointer) tbEdit, "clicked",
                    G_CALLBACK (on_edit1_activate),
                    NULL);
  g_signal_connect ((gpointer) tbSave, "clicked",
                    G_CALLBACK (on_save1_activate),
                    NULL);
  g_signal_connect ((gpointer) bSearch, "clicked",
                    G_CALLBACK (on_bSearch_clicked),
                    NULL);
  g_signal_connect ((gpointer) calendar1, "day_selected_double_click",
                    G_CALLBACK (on_calendar1_day_selected_double_click),
                    NULL);
  g_signal_connect ((gpointer) eDate, "changed",
                    G_CALLBACK (on_eDate_changed),
                    NULL);
  g_signal_connect ((gpointer) rbDay0, "clicked",
                    G_CALLBACK (on_rbDay_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbDay1, "clicked",
                    G_CALLBACK (on_rbDay_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbDay2, "clicked",
                    G_CALLBACK (on_rbDay_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbDay3, "clicked",
                    G_CALLBACK (on_rbDay_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbDay4, "clicked",
                    G_CALLBACK (on_rbDay_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbDay5, "clicked",
                    G_CALLBACK (on_rbDay_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbDay6, "clicked",
                    G_CALLBACK (on_rbDay_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbDay7, "clicked",
                    G_CALLBACK (on_rbDay_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbHour0, "clicked",
                    G_CALLBACK (on_rbHour_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbHour1, "clicked",
                    G_CALLBACK (on_rbHour_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbHour2, "clicked",
                    G_CALLBACK (on_rbHour_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbHour3, "clicked",
                    G_CALLBACK (on_rbHour_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbHour4, "clicked",
                    G_CALLBACK (on_rbHour_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbHours5, "clicked",
                    G_CALLBACK (on_rbHour_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbHour6, "clicked",
                    G_CALLBACK (on_rbHour_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbHour7, "clicked",
                    G_CALLBACK (on_rbHour_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbMinute00, "clicked",
                    G_CALLBACK (on_rbMinute_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbMinute02, "clicked",
                    G_CALLBACK (on_rbMinute_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbMinute05, "clicked",
                    G_CALLBACK (on_rbMinute_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbMinute10, "clicked",
                    G_CALLBACK (on_rbMinute_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbMinute15, "clicked",
                    G_CALLBACK (on_rbMinute_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbMinute20, "clicked",
                    G_CALLBACK (on_rbMinute_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbMinute30, "clicked",
                    G_CALLBACK (on_rbMinute_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbMinute40, "clicked",
                    G_CALLBACK (on_rbMinute_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbMinute45, "clicked",
                    G_CALLBACK (on_rbMinute_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbMinute50, "clicked",
                    G_CALLBACK (on_rbMinute_clicked),
                    NULL);
  g_signal_connect ((gpointer) bCloseWindow, "clicked",
                    G_CALLBACK (on_bCloseWindow_clicked),
                    NULL);
  g_signal_connect ((gpointer) bSleeping, "clicked",
                    G_CALLBACK (on_bSleeping_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ContactMainwindow, ContactMainwindow, "ContactMainwindow");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, menubar1_uiinfo[0].widget, "file1");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, file1_menu_uiinfo[0].widget, "choosePrinter1");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, file1_menu_uiinfo[1].widget, "separator2");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, file1_menu_uiinfo[2].widget, "quit1");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, menubar1_uiinfo[1].widget, "contact1");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, contact1_menu_uiinfo[0].widget, "new1");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, contact1_menu_uiinfo[1].widget, "edit1");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, contact1_menu_uiinfo[2].widget, "separator4");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, contact1_menu_uiinfo[3].widget, "save1");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, contact1_menu_uiinfo[4].widget, "separator3");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, contact1_menu_uiinfo[5].widget, "print1");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, contact1_menu_uiinfo[6].widget, "separator1");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, contact1_menu_uiinfo[7].widget, "delete1");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, tbNew, "tbNew");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, tbEdit, "tbEdit");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, tbSave, "tbSave");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, lFindNumber, "lFindNumber");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, eFindName, "eFindName");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, lFindDesignation, "lFindDesignation");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, eFindCity, "eFindCity");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, bSearch, "bSearch");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, tree1, "tree1");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, table1, "table1");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, table2, "table2");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, cbTime, "cbTime");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, eDate, "eDate");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, label18, "label18");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, label19, "label19");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, label25, "label25");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, cbePriority, "cbePriority");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, label26, "label26");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, cbeStatus, "cbeStatus");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, label21, "label21");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, label22, "label22");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, label23, "label23");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbDay0, "rbDay0");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbDay1, "rbDay1");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbDay2, "rbDay2");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbDay3, "rbDay3");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbDay4, "rbDay4");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbDay5, "rbDay5");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbDay6, "rbDay6");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbDay7, "rbDay7");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbHour0, "rbHour0");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbHour1, "rbHour1");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbHour2, "rbHour2");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbHour3, "rbHour3");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbHour4, "rbHour4");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbHours5, "rbHours5");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbHour6, "rbHour6");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbHour7, "rbHour7");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbMinute00, "rbMinute00");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbMinute02, "rbMinute02");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbMinute05, "rbMinute05");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbMinute10, "rbMinute10");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbMinute15, "rbMinute15");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbMinute20, "rbMinute20");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbMinute30, "rbMinute30");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbMinute40, "rbMinute40");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbMinute45, "rbMinute45");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, rbMinute50, "rbMinute50");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, label20, "label20");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, label27, "label27");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, eAlarmDay, "eAlarmDay");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, eAlarmHour, "eAlarmHour");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, eAlarmMinutes, "eAlarmMinutes");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, label28, "label28");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, tvNotes, "tvNotes");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, label24, "label24");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, tvAddress, "tvAddress");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, bCloseWindow, "bCloseWindow");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, bSleeping, "bSleeping");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, label29, "label29");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, eSleepingTime, "eSleepingTime");
  GLADE_HOOKUP_OBJECT (ContactMainwindow, label16, "label16");
  GLADE_HOOKUP_OBJECT_NO_REF (ContactMainwindow, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (ContactMainwindow), accel_group);

  return ContactMainwindow;
}

