/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

static GnomeUIInfo mi_datei1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Print S_etup..."),
    NULL,
    (gpointer) on_choosePrinter1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("close"),
    NULL,
    (gpointer) on_quit1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-quit",
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo mi_edit_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("gtk-undo"),
    NULL,
    (gpointer) on_undo1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("gtk-find"),
    NULL,
    (gpointer) on_find1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("choose"),
    NULL,
    (gpointer) on_chooseAddress_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo mi_address1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("_New"),
    NULL,
    (gpointer) on_new1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-new",
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("_Edit"),
    NULL,
    (gpointer) on_edit1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("_Save"),
    NULL,
    (gpointer) on_save1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-save",
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("_Print"),
    NULL,
    (gpointer) on_print1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-print",
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("_Delete"),
    NULL,
    (gpointer) on_delete1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-delete",
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo mi_bank1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("gtk-new"),
    NULL,
    (gpointer) on_BankNew1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("_Edit"),
    NULL,
    (gpointer) on_BankEdit1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo mi_misc1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Save"),
    NULL,
    (gpointer) on_MiscSave1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-save",
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("_Edit"),
    NULL,
    (gpointer) on_MiscEdit1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo mi_partner1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("_New"),
    NULL,
    (gpointer) on_PartnerNew1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-new",
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("_Edit"),
    NULL,
    (gpointer) on_PartnerEdit1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Save"),
    NULL,
    (gpointer) on_PartnerSave1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-save",
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("gtk-print"),
    NULL,
    (gpointer) on_mi_PartnerPrint1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("_Delete"),
    NULL,
    (gpointer) on_PartnerDelete1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-delete",
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo mi_schedul1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("gtk-new"),
    NULL,
    (gpointer) on_SchedulNew_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("_Edit"),
    NULL,
    (gpointer) on_SchedulEdit1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("gtk-save"),
    NULL,
    (gpointer) on_SchedulSave_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo listAddresses1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Phone"),
    NULL,
    (gpointer) on_liAddressesPhone1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo list_partner1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Phone"),
    NULL,
    (gpointer) on_liAddressesPhone11_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo mi_lists1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_SUBTREE, N_("Addresses"),
    NULL,
    listAddresses1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Partner"),
    NULL,
    list_partner1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo mi_writer1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("NewLetter"),
    NULL,
    (gpointer) on_newletter1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo menubar1_uiinfo[] =
{
  {
    GNOME_APP_UI_SUBTREE, N_("_File"),
    NULL,
    mi_datei1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Edit"),
    NULL,
    mi_edit_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("_Addresses"),
    NULL,
    mi_address1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Bank"),
    NULL,
    mi_bank1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Misc"),
    NULL,
    mi_misc1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("_Partner"),
    NULL,
    mi_partner1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Schedul"),
    NULL,
    mi_schedul1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Lists"),
    NULL,
    mi_lists1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Writer"),
    NULL,
    mi_writer1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

GtkWidget*
create_AddressMainwindow (void)
{
  GtkWidget *AddressMainwindow;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *toolbar1;
  GtkWidget *hbox1;
  GtkWidget *lFindName;
  GtkWidget *eFindName;
  GtkWidget *lFindCity;
  GtkWidget *eFindCity;
  GtkWidget *bSearch;
  GtkWidget *scrolledwindow5;
  GtkWidget *tree1;
  GtkWidget *notebook1;
  GtkWidget *fixed1;
  GtkWidget *hbox4;
  GtkWidget *table4;
  GtkWidget *eAddress;
  GtkWidget *eLastName;
  GtkWidget *eLastName2;
  GtkWidget *eFirstName;
  GtkWidget *eStreet;
  GtkWidget *lAddress;
  GtkWidget *lLastName;
  GtkWidget *lLastName2;
  GtkWidget *lFirstName;
  GtkWidget *lStreet;
  GtkWidget *lZip;
  GtkWidget *lCountry;
  GtkWidget *eCountry;
  GtkWidget *lZip_PB;
  GtkWidget *lState;
  GtkWidget *eState;
  GtkWidget *hbox8;
  GtkWidget *eZip;
  GtkWidget *label38;
  GtkWidget *eCity;
  GtkWidget *hbox9;
  GtkWidget *eZipForPostbox;
  GtkWidget *label39;
  GtkWidget *ePostbox;
  GtkWidget *table5;
  GtkWidget *lPhone;
  GtkWidget *ePhone;
  GtkWidget *lEmail;
  GtkWidget *lFax;
  GtkWidget *eEmail;
  GtkWidget *eFax;
  GtkWidget *lAddress;
  GtkWidget *table7;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *scrolledwindow2;
  GtkWidget *textview1;
  GtkWidget *eAccount;
  GtkWidget *eBCN;
  GtkWidget *lBank;
  GtkWidget *table9;
  GtkWidget *label35;
  GtkWidget *eLine;
  GtkWidget *label36;
  GtkWidget *cbFashion;
  GtkWidget *eFashion;
  GtkWidget *label37;
  GtkWidget *eTaxnumber;
  GtkWidget *chkbCalcTax;
  GtkWidget *label40;
  GtkWidget *combo2;
  GList *combo2_items = NULL;
  GtkWidget *cbPriceGroup;
  GtkWidget *lMisc;
  GtkWidget *table2;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *ePartnerAddress;
  GtkWidget *ePartnerTitular;
  GtkWidget *ePartnerLastname;
  GtkWidget *ePartnerFirstname;
  GtkWidget *lpartnerPhone1;
  GtkWidget *lPartnerPhone2;
  GtkWidget *lPartnerEmail;
  GtkWidget *lPartnerInternet;
  GtkWidget *lPartnerFaxPrivate;
  GtkWidget *ePartnerPhone1;
  GtkWidget *ePartnerPhone2;
  GtkWidget *ePartnerEmail;
  GtkWidget *ePartnerHomepage;
  GtkWidget *ePartnerFaxPrivate;
  GtkWidget *lPartnerFax;
  GtkWidget *ePartnerFax;
  GtkWidget *lPartnerPhone;
  GtkWidget *lpartnerCounty;
  GtkWidget *hbox2;
  GtkWidget *lPartnerZip;
  GtkWidget *ePartnerZip;
  GtkWidget *ePartnerPhone;
  GtkWidget *ePartnerCountry;
  GtkWidget *hbox3;
  GtkWidget *lPartnerCity;
  GtkWidget *ePartnerCity;
  GtkWidget *lPartnerStreet;
  GtkWidget *ePartnerStreet;
  GtkWidget *label22;
  GtkWidget *ePartnerState;
  GtkWidget *label23;
  GtkWidget *eBirthday;
  GtkWidget *lPartner;
  GtkWidget *table8;
  GtkWidget *label31;
  GtkWidget *scrolledwindow3;
  GtkWidget *eSchedulNotes;
  GtkWidget *eShortRemark;
  GtkWidget *hbox5;
  GtkWidget *label34;
  GtkWidget *eSchedulPriority;
  GtkWidget *label32;
  GtkWidget *hbox6;
  GtkWidget *label33;
  GtkWidget *combo1;
  GtkWidget *eSchedulProcess;
  GtkWidget *hbox7;
  GtkWidget *label30;
  GtkWidget *eSchedulTime;
  GtkWidget *eSchedulDate;
  GtkWidget *label29;
  GtkWidget *calendar1;
  GtkWidget *vbox2;
  GtkWidget *hscale1;
  GtkWidget *vscale1;
  GtkWidget *lSchedul;

  AddressMainwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (AddressMainwindow, 1024, 768);
  gtk_window_set_title (GTK_WINDOW (AddressMainwindow), _("Adresses"));
  gtk_window_set_default_size (GTK_WINDOW (AddressMainwindow), 1024, 768);

  vbox1 = gtk_vbox_new (FALSE, 17);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (AddressMainwindow), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);
  gnome_app_fill_menu (GTK_MENU_SHELL (menubar1), menubar1_uiinfo,
                       NULL, FALSE, 0);

  gtk_widget_set_sensitive (mi_edit_menu_uiinfo[2].widget, FALSE);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);

  hbox1 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, FALSE, 0);

  lFindName = gtk_label_new (_("Name1"));
  gtk_widget_show (lFindName);
  gtk_box_pack_start (GTK_BOX (hbox1), lFindName, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (lFindName), GTK_JUSTIFY_CENTER);

  eFindName = gtk_entry_new ();
  gtk_widget_show (eFindName);
  gtk_box_pack_start (GTK_BOX (hbox1), eFindName, FALSE, FALSE, 0);

  lFindCity = gtk_label_new (_("City"));
  gtk_widget_show (lFindCity);
  gtk_box_pack_start (GTK_BOX (hbox1), lFindCity, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (lFindCity), GTK_JUSTIFY_CENTER);

  eFindCity = gtk_entry_new ();
  gtk_widget_show (eFindCity);
  gtk_box_pack_start (GTK_BOX (hbox1), eFindCity, FALSE, FALSE, 0);

  bSearch = gtk_button_new_with_mnemonic (_("Search"));
  gtk_widget_show (bSearch);
  gtk_box_pack_start (GTK_BOX (hbox1), bSearch, FALSE, FALSE, 0);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow5, TRUE, TRUE, 0);
  gtk_widget_set_size_request (scrolledwindow5, -1, 468);

  tree1 = gtk_tree_view_new ();
  gtk_widget_show (tree1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), tree1);
  gtk_widget_set_size_request (tree1, 138, 167);
  GTK_WIDGET_UNSET_FLAGS (tree1, GTK_CAN_FOCUS);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox1), notebook1, TRUE, TRUE, 0);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed1);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_fixed_put (GTK_FIXED (fixed1), hbox4, 6, 8);
  gtk_widget_set_size_request (hbox4, 1054, 640);

  table4 = gtk_table_new (9, 2, FALSE);
  gtk_widget_show (table4);
  gtk_box_pack_start (GTK_BOX (hbox4), table4, TRUE, TRUE, 0);
  gtk_widget_set_size_request (table4, 555, 317);
  gtk_container_set_border_width (GTK_CONTAINER (table4), 8);
  gtk_table_set_row_spacings (GTK_TABLE (table4), 1);
  gtk_table_set_col_spacings (GTK_TABLE (table4), 12);

  eAddress = gtk_entry_new ();
  gtk_widget_show (eAddress);
  gtk_table_attach (GTK_TABLE (table4), eAddress, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (eAddress, 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (eAddress), 30);

  eLastName = gtk_entry_new ();
  gtk_widget_show (eLastName);
  gtk_table_attach (GTK_TABLE (table4), eLastName, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (eLastName, 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (eLastName), 30);

  eLastName2 = gtk_entry_new ();
  gtk_widget_show (eLastName2);
  gtk_table_attach (GTK_TABLE (table4), eLastName2, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (eLastName2, 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (eLastName2), 30);

  eFirstName = gtk_entry_new ();
  gtk_widget_show (eFirstName);
  gtk_table_attach (GTK_TABLE (table4), eFirstName, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (eFirstName, 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (eFirstName), 30);

  eStreet = gtk_entry_new ();
  gtk_widget_show (eStreet);
  gtk_table_attach (GTK_TABLE (table4), eStreet, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (eStreet, 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (eStreet), 30);

  lAddress = gtk_label_new (_("Address"));
  gtk_widget_show (lAddress);
  gtk_table_attach (GTK_TABLE (table4), lAddress, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lAddress, 0, 0);

  lLastName = gtk_label_new (_("Name1"));
  gtk_widget_show (lLastName);
  gtk_table_attach (GTK_TABLE (table4), lLastName, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lLastName, 0, 0);
  gtk_label_set_justify (GTK_LABEL (lLastName), GTK_JUSTIFY_CENTER);

  lLastName2 = gtk_label_new (_("Name2"));
  gtk_widget_show (lLastName2);
  gtk_table_attach (GTK_TABLE (table4), lLastName2, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lLastName2, 0, 0);
  gtk_label_set_justify (GTK_LABEL (lLastName2), GTK_JUSTIFY_CENTER);

  lFirstName = gtk_label_new (_("Firstname"));
  gtk_widget_show (lFirstName);
  gtk_table_attach (GTK_TABLE (table4), lFirstName, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lFirstName, 0, 0);

  lStreet = gtk_label_new (_("Street"));
  gtk_widget_show (lStreet);
  gtk_table_attach (GTK_TABLE (table4), lStreet, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lStreet, 0, 0);

  lZip = gtk_label_new (_("Zip"));
  gtk_widget_show (lZip);
  gtk_table_attach (GTK_TABLE (table4), lZip, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lZip, 0, 0);
  gtk_label_set_justify (GTK_LABEL (lZip), GTK_JUSTIFY_CENTER);

  lCountry = gtk_label_new (_("Country"));
  gtk_widget_show (lCountry);
  gtk_table_attach (GTK_TABLE (table4), lCountry, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lCountry, 0, 0);
  gtk_label_set_justify (GTK_LABEL (lCountry), GTK_JUSTIFY_CENTER);

  eCountry = gtk_entry_new ();
  gtk_widget_show (eCountry);
  gtk_table_attach (GTK_TABLE (table4), eCountry, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (eCountry, 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (eCountry), 30);

  lZip_PB = gtk_label_new (_("Zip for PB"));
  gtk_widget_show (lZip_PB);
  gtk_table_attach (GTK_TABLE (table4), lZip_PB, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lZip_PB, 0, 0);
  gtk_label_set_justify (GTK_LABEL (lZip_PB), GTK_JUSTIFY_CENTER);

  lState = gtk_label_new (_("State"));
  gtk_widget_show (lState);
  gtk_table_attach (GTK_TABLE (table4), lState, 0, 1, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lState, 0, 0);
  gtk_label_set_justify (GTK_LABEL (lState), GTK_JUSTIFY_CENTER);

  eState = gtk_entry_new ();
  gtk_widget_show (eState);
  gtk_table_attach (GTK_TABLE (table4), eState, 1, 2, 8, 9,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (eState, 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (eState), 30);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox8);
  gtk_table_attach (GTK_TABLE (table4), hbox8, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  eZip = gtk_entry_new ();
  gtk_widget_show (eZip);
  gtk_box_pack_start (GTK_BOX (hbox8), eZip, TRUE, TRUE, 0);
  gtk_widget_set_size_request (eZip, 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (eZip), 7);

  label38 = gtk_label_new (_("City"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox8), label38, FALSE, FALSE, 0);

  eCity = gtk_entry_new ();
  gtk_widget_show (eCity);
  gtk_box_pack_start (GTK_BOX (hbox8), eCity, TRUE, TRUE, 0);
  gtk_widget_set_size_request (eCity, 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (eCity), 30);

  hbox9 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox9);
  gtk_table_attach (GTK_TABLE (table4), hbox9, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  eZipForPostbox = gtk_entry_new ();
  gtk_widget_show (eZipForPostbox);
  gtk_box_pack_start (GTK_BOX (hbox9), eZipForPostbox, TRUE, TRUE, 0);
  gtk_widget_set_size_request (eZipForPostbox, 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (eZipForPostbox), 7);

  label39 = gtk_label_new (_("Postbox"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox9), label39, FALSE, FALSE, 0);

  ePostbox = gtk_entry_new ();
  gtk_widget_show (ePostbox);
  gtk_box_pack_start (GTK_BOX (hbox9), ePostbox, TRUE, TRUE, 0);

  table5 = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table5);
  gtk_box_pack_start (GTK_BOX (hbox4), table5, TRUE, TRUE, 0);
  gtk_widget_set_size_request (table5, 355, 106);

  lPhone = gtk_label_new (_("Phone"));
  gtk_widget_show (lPhone);
  gtk_table_attach (GTK_TABLE (table5), lPhone, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lPhone, 0, 0);
  gtk_label_set_justify (GTK_LABEL (lPhone), GTK_JUSTIFY_CENTER);

  ePhone = gtk_entry_new ();
  gtk_widget_show (ePhone);
  gtk_table_attach (GTK_TABLE (table5), ePhone, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (ePhone, 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (ePhone), 30);

  lEmail = gtk_label_new (_("E-Mail"));
  gtk_widget_show (lEmail);
  gtk_table_attach (GTK_TABLE (table5), lEmail, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lEmail, 0, 0);
  gtk_label_set_justify (GTK_LABEL (lEmail), GTK_JUSTIFY_CENTER);

  lFax = gtk_label_new (_("Fax"));
  gtk_widget_show (lFax);
  gtk_table_attach (GTK_TABLE (table5), lFax, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lFax, 0, 0);
  gtk_label_set_justify (GTK_LABEL (lFax), GTK_JUSTIFY_CENTER);

  eEmail = gtk_entry_new ();
  gtk_widget_show (eEmail);
  gtk_table_attach (GTK_TABLE (table5), eEmail, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (eEmail, 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (eEmail), 30);

  eFax = gtk_entry_new ();
  gtk_widget_show (eFax);
  gtk_table_attach (GTK_TABLE (table5), eFax, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (eFax, 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (eFax), 30);

  lAddress = gtk_label_new (_("Addresses"));
  gtk_widget_show (lAddress);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), lAddress);

  table7 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table7);
  gtk_container_add (GTK_CONTAINER (notebook1), table7);

  label26 = gtk_label_new (_("Name of the Bank"));
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table7), label26, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);

  label27 = gtk_label_new (_("Account"));
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table7), label27, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  label28 = gtk_label_new (_("B C N"));
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (table7), label28, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label28), 0, 0.5);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_table_attach (GTK_TABLE (table7), scrolledwindow2, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), textview1);

  eAccount = gtk_entry_new ();
  gtk_widget_show (eAccount);
  gtk_table_attach (GTK_TABLE (table7), eAccount, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  eBCN = gtk_entry_new ();
  gtk_widget_show (eBCN);
  gtk_table_attach (GTK_TABLE (table7), eBCN, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  lBank = gtk_label_new (_("Bank"));
  gtk_widget_show (lBank);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), lBank);

  table9 = gtk_table_new (4, 4, FALSE);
  gtk_widget_show (table9);
  gtk_container_add (GTK_CONTAINER (notebook1), table9);

  label35 = gtk_label_new (_("Line"));
  gtk_widget_show (label35);
  gtk_table_attach (GTK_TABLE (table9), label35, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label35), 0, 0.5);

  eLine = gtk_entry_new ();
  gtk_widget_show (eLine);
  gtk_table_attach (GTK_TABLE (table9), eLine, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label36 = gtk_label_new (_("fashion"));
  gtk_widget_show (label36);
  gtk_table_attach (GTK_TABLE (table9), label36, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label36), 0, 0.5);

  cbFashion = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (cbFashion)->popwin),
                     "GladeParentKey", cbFashion);
  gtk_widget_show (cbFashion);
  gtk_table_attach (GTK_TABLE (table9), cbFashion, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  eFashion = GTK_COMBO (cbFashion)->entry;
  gtk_widget_show (eFashion);
  gtk_editable_set_editable (GTK_EDITABLE (eFashion), FALSE);

  label37 = gtk_label_new (_("Tax-Nr."));
  gtk_widget_show (label37);
  gtk_table_attach (GTK_TABLE (table9), label37, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label37), 0, 0.5);

  eTaxnumber = gtk_entry_new ();
  gtk_widget_show (eTaxnumber);
  gtk_table_attach (GTK_TABLE (table9), eTaxnumber, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  chkbCalcTax = gtk_check_button_new_with_mnemonic (_("to calc Tax"));
  gtk_widget_show (chkbCalcTax);
  gtk_table_attach (GTK_TABLE (table9), chkbCalcTax, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (chkbCalcTax), TRUE);

  label40 = gtk_label_new (_("Price-Group"));
  gtk_widget_show (label40);
  gtk_table_attach (GTK_TABLE (table9), label40, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label40), 0, 0.5);

  combo2 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo2)->popwin),
                     "GladeParentKey", combo2);
  gtk_widget_show (combo2);
  gtk_table_attach (GTK_TABLE (table9), combo2, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  combo2_items = g_list_append (combo2_items, (gpointer) _("Price I"));
  combo2_items = g_list_append (combo2_items, (gpointer) _("Price II"));
  combo2_items = g_list_append (combo2_items, (gpointer) _("Price III"));
  combo2_items = g_list_append (combo2_items, (gpointer) _("Price IV"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo2), combo2_items);
  g_list_free (combo2_items);

  cbPriceGroup = GTK_COMBO (combo2)->entry;
  gtk_widget_show (cbPriceGroup);
  gtk_entry_set_text (GTK_ENTRY (cbPriceGroup), _("Price I"));

  lMisc = gtk_label_new (_("Misc."));
  gtk_widget_show (lMisc);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), lMisc);

  table2 = gtk_table_new (9, 4, FALSE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (notebook1), table2);

  label15 = gtk_label_new (_("Address"));
  gtk_widget_show (label15);
  gtk_table_attach (GTK_TABLE (table2), label15, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label15), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label15), 0, 0.5);

  label16 = gtk_label_new (_("titular"));
  gtk_widget_show (label16);
  gtk_table_attach (GTK_TABLE (table2), label16, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label16), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label16), 0, 0.5);

  label17 = gtk_label_new (_("Lastname"));
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (table2), label17, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label17), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label17), 0, 0.5);

  label18 = gtk_label_new (_("Firstname"));
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (table2), label18, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label18), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0.5);

  ePartnerAddress = gtk_entry_new ();
  gtk_widget_show (ePartnerAddress);
  gtk_table_attach (GTK_TABLE (table2), ePartnerAddress, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  ePartnerTitular = gtk_entry_new ();
  gtk_widget_show (ePartnerTitular);
  gtk_table_attach (GTK_TABLE (table2), ePartnerTitular, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  ePartnerLastname = gtk_entry_new ();
  gtk_widget_show (ePartnerLastname);
  gtk_table_attach (GTK_TABLE (table2), ePartnerLastname, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  ePartnerFirstname = gtk_entry_new ();
  gtk_widget_show (ePartnerFirstname);
  gtk_table_attach (GTK_TABLE (table2), ePartnerFirstname, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  lpartnerPhone1 = gtk_label_new (_("Phone 1"));
  gtk_widget_show (lpartnerPhone1);
  gtk_table_attach (GTK_TABLE (table2), lpartnerPhone1, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lpartnerPhone1), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lpartnerPhone1), 0, 0.5);

  lPartnerPhone2 = gtk_label_new (_("Phone 2"));
  gtk_widget_show (lPartnerPhone2);
  gtk_table_attach (GTK_TABLE (table2), lPartnerPhone2, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lPartnerPhone2), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lPartnerPhone2), 0, 0.5);

  lPartnerEmail = gtk_label_new (_("E-Mail"));
  gtk_widget_show (lPartnerEmail);
  gtk_table_attach (GTK_TABLE (table2), lPartnerEmail, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lPartnerEmail), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lPartnerEmail), 0, 0.5);

  lPartnerInternet = gtk_label_new (_("Homepage"));
  gtk_widget_show (lPartnerInternet);
  gtk_table_attach (GTK_TABLE (table2), lPartnerInternet, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lPartnerInternet), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lPartnerInternet), 0, 0.5);

  lPartnerFaxPrivate = gtk_label_new (_("Fax"));
  gtk_widget_show (lPartnerFaxPrivate);
  gtk_table_attach (GTK_TABLE (table2), lPartnerFaxPrivate, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lPartnerFaxPrivate), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lPartnerFaxPrivate), 0, 0.5);

  ePartnerPhone1 = gtk_entry_new ();
  gtk_widget_show (ePartnerPhone1);
  gtk_table_attach (GTK_TABLE (table2), ePartnerPhone1, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  ePartnerPhone2 = gtk_entry_new ();
  gtk_widget_show (ePartnerPhone2);
  gtk_table_attach (GTK_TABLE (table2), ePartnerPhone2, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  ePartnerEmail = gtk_entry_new ();
  gtk_widget_show (ePartnerEmail);
  gtk_table_attach (GTK_TABLE (table2), ePartnerEmail, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  ePartnerHomepage = gtk_entry_new ();
  gtk_widget_show (ePartnerHomepage);
  gtk_table_attach (GTK_TABLE (table2), ePartnerHomepage, 3, 4, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  ePartnerFaxPrivate = gtk_entry_new ();
  gtk_widget_show (ePartnerFaxPrivate);
  gtk_table_attach (GTK_TABLE (table2), ePartnerFaxPrivate, 3, 4, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  lPartnerFax = gtk_label_new (_("Fax in company"));
  gtk_widget_show (lPartnerFax);
  gtk_table_attach (GTK_TABLE (table2), lPartnerFax, 0, 1, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lPartnerFax), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lPartnerFax), 0, 0.5);

  ePartnerFax = gtk_entry_new ();
  gtk_widget_show (ePartnerFax);
  gtk_table_attach (GTK_TABLE (table2), ePartnerFax, 1, 2, 8, 9,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  lPartnerPhone = gtk_label_new (_("Phone in Company"));
  gtk_widget_show (lPartnerPhone);
  gtk_table_attach (GTK_TABLE (table2), lPartnerPhone, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lPartnerPhone), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lPartnerPhone), 0, 0.5);

  lpartnerCounty = gtk_label_new (_("Country"));
  gtk_widget_show (lpartnerCounty);
  gtk_table_attach (GTK_TABLE (table2), lpartnerCounty, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lpartnerCounty), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lpartnerCounty), 0, 0.5);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_table_attach (GTK_TABLE (table2), hbox2, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  lPartnerZip = gtk_label_new (_("Zip"));
  gtk_widget_show (lPartnerZip);
  gtk_box_pack_start (GTK_BOX (hbox2), lPartnerZip, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (lPartnerZip), GTK_JUSTIFY_CENTER);

  ePartnerZip = gtk_entry_new ();
  gtk_widget_show (ePartnerZip);
  gtk_box_pack_start (GTK_BOX (hbox2), ePartnerZip, TRUE, TRUE, 0);

  ePartnerPhone = gtk_entry_new ();
  gtk_widget_show (ePartnerPhone);
  gtk_table_attach (GTK_TABLE (table2), ePartnerPhone, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  ePartnerCountry = gtk_entry_new ();
  gtk_widget_show (ePartnerCountry);
  gtk_table_attach (GTK_TABLE (table2), ePartnerCountry, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_table_attach (GTK_TABLE (table2), hbox3, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  lPartnerCity = gtk_label_new (_("City"));
  gtk_widget_show (lPartnerCity);
  gtk_box_pack_start (GTK_BOX (hbox3), lPartnerCity, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (lPartnerCity), GTK_JUSTIFY_CENTER);

  ePartnerCity = gtk_entry_new ();
  gtk_widget_show (ePartnerCity);
  gtk_box_pack_start (GTK_BOX (hbox3), ePartnerCity, TRUE, TRUE, 0);

  lPartnerStreet = gtk_label_new (_("Street"));
  gtk_widget_show (lPartnerStreet);
  gtk_table_attach (GTK_TABLE (table2), lPartnerStreet, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lPartnerStreet), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lPartnerStreet), 0, 0.5);

  ePartnerStreet = gtk_entry_new ();
  gtk_widget_show (ePartnerStreet);
  gtk_table_attach (GTK_TABLE (table2), ePartnerStreet, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label22 = gtk_label_new (_("State"));
  gtk_widget_show (label22);
  gtk_table_attach (GTK_TABLE (table2), label22, 2, 3, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0.5);

  ePartnerState = gtk_entry_new ();
  gtk_widget_show (ePartnerState);
  gtk_table_attach (GTK_TABLE (table2), ePartnerState, 3, 4, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label23 = gtk_label_new (_("Birthday"));
  gtk_widget_show (label23);
  gtk_table_attach (GTK_TABLE (table2), label23, 2, 3, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);

  eBirthday = gtk_entry_new ();
  gtk_widget_show (eBirthday);
  gtk_table_attach (GTK_TABLE (table2), eBirthday, 3, 4, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  lPartner = gtk_label_new (_("Partner"));
  gtk_widget_show (lPartner);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), lPartner);

  table8 = gtk_table_new (4, 4, FALSE);
  gtk_widget_show (table8);
  gtk_container_add (GTK_CONTAINER (notebook1), table8);

  label31 = gtk_label_new (_("short Remark"));
  gtk_widget_show (label31);
  gtk_table_attach (GTK_TABLE (table8), label31, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label31), 0, 0.5);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_table_attach (GTK_TABLE (table8), scrolledwindow3, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  eSchedulNotes = gtk_text_view_new ();
  gtk_widget_show (eSchedulNotes);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), eSchedulNotes);

  eShortRemark = gtk_entry_new ();
  gtk_widget_show (eShortRemark);
  gtk_table_attach (GTK_TABLE (table8), eShortRemark, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox5);
  gtk_table_attach (GTK_TABLE (table8), hbox5, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label34 = gtk_label_new (_("Priority"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox5), label34, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label34), 0, 0.5);

  eSchedulPriority = gtk_entry_new ();
  gtk_widget_show (eSchedulPriority);
  gtk_box_pack_start (GTK_BOX (hbox5), eSchedulPriority, TRUE, TRUE, 0);

  label32 = gtk_label_new (_("Note"));
  gtk_widget_show (label32);
  gtk_table_attach (GTK_TABLE (table8), label32, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label32), 0, 0.5);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox6);
  gtk_table_attach (GTK_TABLE (table8), hbox6, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label33 = gtk_label_new (_("Process"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox6), label33, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label33), 0, 0.5);

  combo1 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo1)->popwin),
                     "GladeParentKey", combo1);
  gtk_widget_show (combo1);
  gtk_box_pack_start (GTK_BOX (hbox6), combo1, TRUE, TRUE, 0);

  eSchedulProcess = GTK_COMBO (combo1)->entry;
  gtk_widget_show (eSchedulProcess);
  gtk_entry_set_max_length (GTK_ENTRY (eSchedulProcess), 5);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox7);
  gtk_table_attach (GTK_TABLE (table8), hbox7, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label30 = gtk_label_new (_("Time"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox7), label30, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label30), 0, 0.5);

  eSchedulTime = gtk_entry_new ();
  gtk_widget_show (eSchedulTime);
  gtk_box_pack_start (GTK_BOX (hbox7), eSchedulTime, TRUE, TRUE, 0);

  eSchedulDate = gtk_entry_new ();
  gtk_widget_show (eSchedulDate);
  gtk_table_attach (GTK_TABLE (table8), eSchedulDate, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label29 = gtk_label_new (_("Date"));
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (table8), label29, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label29), 0, 0.5);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_table_attach (GTK_TABLE (table8), calendar1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES
                                | GTK_CALENDAR_WEEK_START_MONDAY);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_table_attach (GTK_TABLE (table8), vbox2, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hscale1 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (11, 0, 23, 1, 1, 0)));
  gtk_widget_show (hscale1);
  gtk_box_pack_start (GTK_BOX (vbox2), hscale1, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (hscale1), 0);

  vscale1 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (30, 0, 59, 1, 15, 0)));
  gtk_widget_show (vscale1);
  gtk_box_pack_start (GTK_BOX (vbox2), vscale1, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (vscale1), 0);

  lSchedul = gtk_label_new (_("Schedul"));
  gtk_widget_show (lSchedul);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), lSchedul);

  g_signal_connect ((gpointer) bSearch, "clicked",
                    G_CALLBACK (on_bSearch_clicked),
                    NULL);
  g_signal_connect ((gpointer) notebook1, "switch_page",
                    G_CALLBACK (on_notebook1_switch_page),
                    NULL);
  g_signal_connect ((gpointer) eSchedulDate, "changed",
                    G_CALLBACK (on_eSchedulDate_changed),
                    NULL);
  g_signal_connect ((gpointer) calendar1, "day_selected",
                    G_CALLBACK (on_calendar1_day_selected),
                    NULL);
  g_signal_connect ((gpointer) hscale1, "value_changed",
                    G_CALLBACK (on_hscale1_value_changed),
                    NULL);
  g_signal_connect ((gpointer) vscale1, "value_changed",
                    G_CALLBACK (on_vscale1_value_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (AddressMainwindow, AddressMainwindow, "AddressMainwindow");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, menubar1_uiinfo[0].widget, "mi_datei1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_datei1_menu_uiinfo[0].widget, "mi_choosePrinter1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_datei1_menu_uiinfo[1].widget, "separator2");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_datei1_menu_uiinfo[2].widget, "mi_quit1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, menubar1_uiinfo[1].widget, "mi_edit");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_edit_menu_uiinfo[0].widget, "undo1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_edit_menu_uiinfo[1].widget, "find1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_edit_menu_uiinfo[2].widget, "chooseAddress");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, menubar1_uiinfo[2].widget, "mi_address1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_address1_menu_uiinfo[0].widget, "mi_new1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_address1_menu_uiinfo[1].widget, "mi_edit1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_address1_menu_uiinfo[2].widget, "mi_save1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_address1_menu_uiinfo[3].widget, "trennlinie2");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_address1_menu_uiinfo[4].widget, "mi_print1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_address1_menu_uiinfo[5].widget, "trennlinie5");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_address1_menu_uiinfo[6].widget, "mi_clear1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, menubar1_uiinfo[3].widget, "mi_bank1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_bank1_menu_uiinfo[0].widget, "new1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_bank1_menu_uiinfo[1].widget, "mi_BankEdit1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, menubar1_uiinfo[4].widget, "mi_misc1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_misc1_menu_uiinfo[0].widget, "mi_MiscSave1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_misc1_menu_uiinfo[1].widget, "mi_MiscEdit1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, menubar1_uiinfo[5].widget, "mi_partner1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_partner1_menu_uiinfo[0].widget, "mi_PartnerNew1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_partner1_menu_uiinfo[1].widget, "mi_PartnerEdit1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_partner1_menu_uiinfo[2].widget, "mi_PartnerSave1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_partner1_menu_uiinfo[3].widget, "separator1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_partner1_menu_uiinfo[4].widget, "mi_partnerPrint1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_partner1_menu_uiinfo[5].widget, "separator3");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_partner1_menu_uiinfo[6].widget, "mi_PartnerDelete1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, menubar1_uiinfo[6].widget, "mi_schedul1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_schedul1_menu_uiinfo[0].widget, "mi_SchedulNew");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_schedul1_menu_uiinfo[1].widget, "mi_SchedulEdit1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_schedul1_menu_uiinfo[2].widget, "mi_schedulSave");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, menubar1_uiinfo[7].widget, "mi_lists1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_lists1_menu_uiinfo[0].widget, "listAddresses1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, listAddresses1_menu_uiinfo[0].widget, "PhoneList");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_lists1_menu_uiinfo[1].widget, "list_partner1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, list_partner1_menu_uiinfo[0].widget, "phone1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, menubar1_uiinfo[8].widget, "mi_writer1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, mi_writer1_menu_uiinfo[0].widget, "newletter1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lFindName, "lFindName");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eFindName, "eFindName");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lFindCity, "lFindCity");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eFindCity, "eFindCity");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, bSearch, "bSearch");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, tree1, "tree1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, table4, "table4");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eAddress, "eAddress");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eLastName, "eLastName");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eLastName2, "eLastName2");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eFirstName, "eFirstName");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eStreet, "eStreet");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lAddress, "lAddress");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lLastName, "lLastName");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lLastName2, "lLastName2");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lFirstName, "lFirstName");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lStreet, "lStreet");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lZip, "lZip");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lCountry, "lCountry");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eCountry, "eCountry");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lZip_PB, "lZip_PB");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lState, "lState");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eState, "eState");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eZip, "eZip");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, label38, "label38");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eCity, "eCity");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eZipForPostbox, "eZipForPostbox");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, label39, "label39");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, ePostbox, "ePostbox");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, table5, "table5");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lPhone, "lPhone");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, ePhone, "ePhone");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lEmail, "lEmail");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lFax, "lFax");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eEmail, "eEmail");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eFax, "eFax");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lAddress, "lAddress");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, table7, "table7");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, label26, "label26");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, label27, "label27");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, label28, "label28");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eAccount, "eAccount");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eBCN, "eBCN");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lBank, "lBank");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, table9, "table9");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, label35, "label35");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eLine, "eLine");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, label36, "label36");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, cbFashion, "cbFashion");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eFashion, "eFashion");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, label37, "label37");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eTaxnumber, "eTaxnumber");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, chkbCalcTax, "chkbCalcTax");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, label40, "label40");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, combo2, "combo2");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, cbPriceGroup, "cbPriceGroup");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lMisc, "lMisc");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, table2, "table2");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, label15, "label15");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, label16, "label16");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, label17, "label17");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, label18, "label18");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, ePartnerAddress, "ePartnerAddress");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, ePartnerTitular, "ePartnerTitular");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, ePartnerLastname, "ePartnerLastname");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, ePartnerFirstname, "ePartnerFirstname");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lpartnerPhone1, "lpartnerPhone1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lPartnerPhone2, "lPartnerPhone2");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lPartnerEmail, "lPartnerEmail");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lPartnerInternet, "lPartnerInternet");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lPartnerFaxPrivate, "lPartnerFaxPrivate");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, ePartnerPhone1, "ePartnerPhone1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, ePartnerPhone2, "ePartnerPhone2");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, ePartnerEmail, "ePartnerEmail");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, ePartnerHomepage, "ePartnerHomepage");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, ePartnerFaxPrivate, "ePartnerFaxPrivate");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lPartnerFax, "lPartnerFax");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, ePartnerFax, "ePartnerFax");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lPartnerPhone, "lPartnerPhone");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lpartnerCounty, "lpartnerCounty");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lPartnerZip, "lPartnerZip");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, ePartnerZip, "ePartnerZip");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, ePartnerPhone, "ePartnerPhone");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, ePartnerCountry, "ePartnerCountry");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lPartnerCity, "lPartnerCity");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, ePartnerCity, "ePartnerCity");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lPartnerStreet, "lPartnerStreet");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, ePartnerStreet, "ePartnerStreet");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, label22, "label22");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, ePartnerState, "ePartnerState");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, label23, "label23");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eBirthday, "eBirthday");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lPartner, "lPartner");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, table8, "table8");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, label31, "label31");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eSchedulNotes, "eSchedulNotes");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eShortRemark, "eShortRemark");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, label34, "label34");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eSchedulPriority, "eSchedulPriority");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, label32, "label32");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, label33, "label33");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, combo1, "combo1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eSchedulProcess, "eSchedulProcess");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, label30, "label30");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eSchedulTime, "eSchedulTime");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, eSchedulDate, "eSchedulDate");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, label29, "label29");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, hscale1, "hscale1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, vscale1, "vscale1");
  GLADE_HOOKUP_OBJECT (AddressMainwindow, lSchedul, "lSchedul");

  gtk_widget_grab_default (eFashion);
  return AddressMainwindow;
}

