/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

static GnomeUIInfo file1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Print S_etup"),
    NULL,
    (gpointer) on_print_setup1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_EXIT_ITEM (on_quit1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo stock1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("New"),
    NULL,
    (gpointer) on_New1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Edit"),
    NULL,
    (gpointer) on_Edit1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("Save"),
    NULL,
    (gpointer) on_Save1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("Clear"),
    NULL,
    (gpointer) on_Delete1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo goods1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("New"),
    NULL,
    (gpointer) on_GoodsNew1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Edit"),
    NULL,
    (gpointer) on_GoodsEdit1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("Save"),
    NULL,
    (gpointer) on_GoodsSave1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("Clear"),
    NULL,
    (gpointer) on_GoodsClear1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo menubar1_uiinfo[] =
{
  {
    GNOME_APP_UI_SUBTREE, N_("_File"),
    NULL,
    file1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Stock"),
    NULL,
    stock1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Goods"),
    NULL,
    goods1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

GtkWidget*
create_StockMainwindow (void)
{
  GtkWidget *StockMainwindow;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *toolbar1;
  GtkWidget *hbox1;
  GtkWidget *lFindNumber;
  GtkWidget *eFindName;
  GtkWidget *lFindDesignation;
  GtkWidget *eFindCity;
  GtkWidget *bSearch;
  GtkWidget *scrolledwindow1;
  GtkWidget *tree1;
  GtkWidget *notebook1;
  GtkWidget *table1;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *eStockName;
  GtkWidget *eStockDesignation;
  GtkWidget *label16;
  GtkWidget *eStockAddress;
  GtkWidget *label26;
  GtkWidget *eStockPhone;
  GtkWidget *label4;
  GtkWidget *table2;
  GtkWidget *hbox12;
  GtkWidget *label19;
  GtkWidget *bArticleSearch;
  GtkWidget *eArticleID;
  GtkWidget *eGoodsArticleDesignation;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *eGoodsUnit;
  GtkWidget *eGoodsWrapping;
  GtkWidget *eGoodsQuantumPerWrap;
  GtkWidget *label24;
  GtkWidget *eToEmbed;
  GtkWidget *label25;
  GtkWidget *eRollOut;
  GtkWidget *label27;
  GtkWidget *eGoodsDesignation;
  GtkWidget *label23;
  GtkWidget *eActualStock;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *eGoodsReferenceNumber;
  GtkWidget *eGoodsDate;
  GtkWidget *label17;
  GtkWidget *entry13;

  StockMainwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (StockMainwindow, 0, 0);
  gtk_window_set_title (GTK_WINDOW (StockMainwindow), _("Stock"));

  vbox1 = gtk_vbox_new (FALSE, 17);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (StockMainwindow), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);
  gnome_app_fill_menu (GTK_MENU_SHELL (menubar1), menubar1_uiinfo,
                       NULL, FALSE, 0);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);

  hbox1 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, FALSE, 0);

  lFindNumber = gtk_label_new (_("Number"));
  gtk_widget_show (lFindNumber);
  gtk_box_pack_start (GTK_BOX (hbox1), lFindNumber, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (lFindNumber), GTK_JUSTIFY_CENTER);

  eFindName = gtk_entry_new ();
  gtk_widget_show (eFindName);
  gtk_box_pack_start (GTK_BOX (hbox1), eFindName, FALSE, FALSE, 0);

  lFindDesignation = gtk_label_new (_("Designation"));
  gtk_widget_show (lFindDesignation);
  gtk_box_pack_start (GTK_BOX (hbox1), lFindDesignation, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (lFindDesignation), GTK_JUSTIFY_CENTER);

  eFindCity = gtk_entry_new ();
  gtk_widget_show (eFindCity);
  gtk_box_pack_start (GTK_BOX (hbox1), eFindCity, FALSE, FALSE, 0);

  bSearch = gtk_button_new_with_mnemonic (_("Search"));
  gtk_widget_show (bSearch);
  gtk_box_pack_start (GTK_BOX (hbox1), bSearch, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow1, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (scrolledwindow1, GTK_CAN_FOCUS);

  tree1 = gtk_tree_view_new ();
  gtk_widget_show (tree1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), tree1);
  gtk_widget_set_size_request (tree1, -1, 106);
  gtk_container_set_border_width (GTK_CONTAINER (tree1), 5);
  GTK_WIDGET_UNSET_FLAGS (tree1, GTK_CAN_FOCUS);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox1), notebook1, TRUE, TRUE, 0);

  table1 = gtk_table_new (6, 4, FALSE);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (notebook1), table1);

  label14 = gtk_label_new (_("Name"));
  gtk_widget_show (label14);
  gtk_table_attach (GTK_TABLE (table1), label14, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);

  label15 = gtk_label_new (_("Designation"));
  gtk_widget_show (label15);
  gtk_table_attach (GTK_TABLE (table1), label15, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label15), 0, 0.5);

  eStockName = gtk_entry_new ();
  gtk_widget_show (eStockName);
  gtk_table_attach (GTK_TABLE (table1), eStockName, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  eStockDesignation = gtk_entry_new ();
  gtk_widget_show (eStockDesignation);
  gtk_table_attach (GTK_TABLE (table1), eStockDesignation, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label16 = gtk_label_new (_("Address"));
  gtk_widget_show (label16);
  gtk_table_attach (GTK_TABLE (table1), label16, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label16), 0, 0.5);

  eStockAddress = gtk_entry_new ();
  gtk_widget_show (eStockAddress);
  gtk_table_attach (GTK_TABLE (table1), eStockAddress, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label26 = gtk_label_new (_("Phone"));
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table1), label26, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);

  eStockPhone = gtk_entry_new ();
  gtk_widget_show (eStockPhone);
  gtk_table_attach (GTK_TABLE (table1), eStockPhone, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label4 = gtk_label_new (_("Stock"));
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label4);

  table2 = gtk_table_new (8, 4, FALSE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (notebook1), table2);

  hbox12 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox12);
  gtk_table_attach (GTK_TABLE (table2), hbox12, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  label19 = gtk_label_new (_("Article"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox12), label19, FALSE, FALSE, 0);

  bArticleSearch = gtk_button_new_with_mnemonic (_("Search..."));
  gtk_widget_show (bArticleSearch);
  gtk_box_pack_start (GTK_BOX (hbox12), bArticleSearch, FALSE, FALSE, 0);

  eArticleID = gtk_entry_new ();
  gtk_widget_show (eArticleID);
  gtk_box_pack_start (GTK_BOX (hbox12), eArticleID, TRUE, TRUE, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (eArticleID), 8);

  eGoodsArticleDesignation = gtk_entry_new ();
  gtk_widget_show (eGoodsArticleDesignation);
  gtk_table_attach (GTK_TABLE (table2), eGoodsArticleDesignation, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (eGoodsArticleDesignation), FALSE);

  label20 = gtk_label_new (_("Unit"));
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table2), label20, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  label21 = gtk_label_new (_("Wrapping"));
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (table2), label21, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label21), 0, 0.5);

  label22 = gtk_label_new (_("Qu. per Wrap."));
  gtk_widget_show (label22);
  gtk_table_attach (GTK_TABLE (table2), label22, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0.5);

  eGoodsUnit = gtk_entry_new ();
  gtk_widget_show (eGoodsUnit);
  gtk_table_attach (GTK_TABLE (table2), eGoodsUnit, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (eGoodsUnit), FALSE);

  eGoodsWrapping = gtk_entry_new ();
  gtk_widget_show (eGoodsWrapping);
  gtk_table_attach (GTK_TABLE (table2), eGoodsWrapping, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (eGoodsWrapping), FALSE);

  eGoodsQuantumPerWrap = gtk_entry_new ();
  gtk_widget_show (eGoodsQuantumPerWrap);
  gtk_table_attach (GTK_TABLE (table2), eGoodsQuantumPerWrap, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (eGoodsQuantumPerWrap), FALSE);

  label24 = gtk_label_new (_("to embed"));
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (table2), label24, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);

  eToEmbed = gtk_entry_new ();
  gtk_widget_show (eToEmbed);
  gtk_table_attach (GTK_TABLE (table2), eToEmbed, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label25 = gtk_label_new (_("to roll out"));
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table2), label25, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  eRollOut = gtk_entry_new ();
  gtk_widget_show (eRollOut);
  gtk_table_attach (GTK_TABLE (table2), eRollOut, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label27 = gtk_label_new (_("Designation"));
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table2), label27, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  eGoodsDesignation = gtk_entry_new ();
  gtk_widget_show (eGoodsDesignation);
  gtk_table_attach (GTK_TABLE (table2), eGoodsDesignation, 3, 4, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label23 = gtk_label_new (_("actual stock"));
  gtk_widget_show (label23);
  gtk_table_attach (GTK_TABLE (table2), label23, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);

  eActualStock = gtk_entry_new ();
  gtk_widget_show (eActualStock);
  gtk_table_attach (GTK_TABLE (table2), eActualStock, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (eActualStock), FALSE);

  label28 = gtk_label_new (_("Date"));
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (table2), label28, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label28), 0, 0.5);

  label29 = gtk_label_new (_("Reference Nr."));
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (table2), label29, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label29), 0, 0.5);

  eGoodsReferenceNumber = gtk_entry_new ();
  gtk_widget_show (eGoodsReferenceNumber);
  gtk_table_attach (GTK_TABLE (table2), eGoodsReferenceNumber, 3, 4, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  eGoodsDate = gnome_date_edit_new ((time_t) 0, TRUE, TRUE);
  gtk_widget_show (eGoodsDate);
  gtk_table_attach (GTK_TABLE (table2), eGoodsDate, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label17 = gtk_label_new (_("Goods"));
  gtk_widget_show (label17);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label17);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_box_pack_start (GTK_BOX (vbox1), entry13, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) bSearch, "clicked",
                    G_CALLBACK (on_bSearch_clicked),
                    NULL);
  g_signal_connect ((gpointer) notebook1, "switch_page",
                    G_CALLBACK (on_notebook1_switch_page),
                    NULL);
  g_signal_connect ((gpointer) bArticleSearch, "clicked",
                    G_CALLBACK (on_bArticleSearch_clicked),
                    NULL);
  g_signal_connect ((gpointer) eArticleID, "changed",
                    G_CALLBACK (on_eArticleID_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (StockMainwindow, StockMainwindow, "StockMainwindow");
  GLADE_HOOKUP_OBJECT (StockMainwindow, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (StockMainwindow, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (StockMainwindow, menubar1_uiinfo[0].widget, "file1");
  GLADE_HOOKUP_OBJECT (StockMainwindow, file1_menu_uiinfo[0].widget, "print_setup1");
  GLADE_HOOKUP_OBJECT (StockMainwindow, file1_menu_uiinfo[1].widget, "separator15");
  GLADE_HOOKUP_OBJECT (StockMainwindow, file1_menu_uiinfo[2].widget, "quit1");
  GLADE_HOOKUP_OBJECT (StockMainwindow, menubar1_uiinfo[1].widget, "stock1");
  GLADE_HOOKUP_OBJECT (StockMainwindow, stock1_menu_uiinfo[0].widget, "New1");
  GLADE_HOOKUP_OBJECT (StockMainwindow, stock1_menu_uiinfo[1].widget, "Edit1");
  GLADE_HOOKUP_OBJECT (StockMainwindow, stock1_menu_uiinfo[2].widget, "separator11");
  GLADE_HOOKUP_OBJECT (StockMainwindow, stock1_menu_uiinfo[3].widget, "Save1");
  GLADE_HOOKUP_OBJECT (StockMainwindow, stock1_menu_uiinfo[4].widget, "separator12");
  GLADE_HOOKUP_OBJECT (StockMainwindow, stock1_menu_uiinfo[5].widget, "Delete1");
  GLADE_HOOKUP_OBJECT (StockMainwindow, menubar1_uiinfo[2].widget, "goods1");
  GLADE_HOOKUP_OBJECT (StockMainwindow, goods1_menu_uiinfo[0].widget, "goodsnew1");
  GLADE_HOOKUP_OBJECT (StockMainwindow, goods1_menu_uiinfo[1].widget, "goodsedit1");
  GLADE_HOOKUP_OBJECT (StockMainwindow, goods1_menu_uiinfo[2].widget, "separator13");
  GLADE_HOOKUP_OBJECT (StockMainwindow, goods1_menu_uiinfo[3].widget, "goodssave1");
  GLADE_HOOKUP_OBJECT (StockMainwindow, goods1_menu_uiinfo[4].widget, "separator14");
  GLADE_HOOKUP_OBJECT (StockMainwindow, goods1_menu_uiinfo[5].widget, "goodsclear1");
  GLADE_HOOKUP_OBJECT (StockMainwindow, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (StockMainwindow, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (StockMainwindow, lFindNumber, "lFindNumber");
  GLADE_HOOKUP_OBJECT (StockMainwindow, eFindName, "eFindName");
  GLADE_HOOKUP_OBJECT (StockMainwindow, lFindDesignation, "lFindDesignation");
  GLADE_HOOKUP_OBJECT (StockMainwindow, eFindCity, "eFindCity");
  GLADE_HOOKUP_OBJECT (StockMainwindow, bSearch, "bSearch");
  GLADE_HOOKUP_OBJECT (StockMainwindow, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (StockMainwindow, tree1, "tree1");
  GLADE_HOOKUP_OBJECT (StockMainwindow, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (StockMainwindow, table1, "table1");
  GLADE_HOOKUP_OBJECT (StockMainwindow, label14, "label14");
  GLADE_HOOKUP_OBJECT (StockMainwindow, label15, "label15");
  GLADE_HOOKUP_OBJECT (StockMainwindow, eStockName, "eStockName");
  GLADE_HOOKUP_OBJECT (StockMainwindow, eStockDesignation, "eStockDesignation");
  GLADE_HOOKUP_OBJECT (StockMainwindow, label16, "label16");
  GLADE_HOOKUP_OBJECT (StockMainwindow, eStockAddress, "eStockAddress");
  GLADE_HOOKUP_OBJECT (StockMainwindow, label26, "label26");
  GLADE_HOOKUP_OBJECT (StockMainwindow, eStockPhone, "eStockPhone");
  GLADE_HOOKUP_OBJECT (StockMainwindow, label4, "label4");
  GLADE_HOOKUP_OBJECT (StockMainwindow, table2, "table2");
  GLADE_HOOKUP_OBJECT (StockMainwindow, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (StockMainwindow, label19, "label19");
  GLADE_HOOKUP_OBJECT (StockMainwindow, bArticleSearch, "bArticleSearch");
  GLADE_HOOKUP_OBJECT (StockMainwindow, eArticleID, "eArticleID");
  GLADE_HOOKUP_OBJECT (StockMainwindow, eGoodsArticleDesignation, "eGoodsArticleDesignation");
  GLADE_HOOKUP_OBJECT (StockMainwindow, label20, "label20");
  GLADE_HOOKUP_OBJECT (StockMainwindow, label21, "label21");
  GLADE_HOOKUP_OBJECT (StockMainwindow, label22, "label22");
  GLADE_HOOKUP_OBJECT (StockMainwindow, eGoodsUnit, "eGoodsUnit");
  GLADE_HOOKUP_OBJECT (StockMainwindow, eGoodsWrapping, "eGoodsWrapping");
  GLADE_HOOKUP_OBJECT (StockMainwindow, eGoodsQuantumPerWrap, "eGoodsQuantumPerWrap");
  GLADE_HOOKUP_OBJECT (StockMainwindow, label24, "label24");
  GLADE_HOOKUP_OBJECT (StockMainwindow, eToEmbed, "eToEmbed");
  GLADE_HOOKUP_OBJECT (StockMainwindow, label25, "label25");
  GLADE_HOOKUP_OBJECT (StockMainwindow, eRollOut, "eRollOut");
  GLADE_HOOKUP_OBJECT (StockMainwindow, label27, "label27");
  GLADE_HOOKUP_OBJECT (StockMainwindow, eGoodsDesignation, "eGoodsDesignation");
  GLADE_HOOKUP_OBJECT (StockMainwindow, label23, "label23");
  GLADE_HOOKUP_OBJECT (StockMainwindow, eActualStock, "eActualStock");
  GLADE_HOOKUP_OBJECT (StockMainwindow, label28, "label28");
  GLADE_HOOKUP_OBJECT (StockMainwindow, label29, "label29");
  GLADE_HOOKUP_OBJECT (StockMainwindow, eGoodsReferenceNumber, "eGoodsReferenceNumber");
  GLADE_HOOKUP_OBJECT (StockMainwindow, eGoodsDate, "eGoodsDate");
  GLADE_HOOKUP_OBJECT (StockMainwindow, label17, "label17");
  GLADE_HOOKUP_OBJECT (StockMainwindow, entry13, "entry13");

  return StockMainwindow;
}

