/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

static GnomeUIInfo menuitem1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Print S_etup..."),
    NULL,
    (gpointer) on_choosePrinter1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("close"),
    NULL,
    (gpointer) on_quit1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo edit_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("choose"),
    NULL,
    (gpointer) on_chooseArticle_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo mi_article1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("New"),
    NULL,
    (gpointer) on_new1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Edit"),
    NULL,
    (gpointer) on_edit1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Save"),
    NULL,
    (gpointer) on_save1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("Print"),
    NULL,
    (gpointer) on_print1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("Clear"),
    NULL,
    (gpointer) on_clear1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo mi_purchase1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("New"),
    NULL,
    (gpointer) on_PurchaseNew1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Edit"),
    NULL,
    (gpointer) on_PurchaseEdit1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Save"),
    NULL,
    (gpointer) on_PurchaseSave1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("Clear"),
    NULL,
    (gpointer) on_PurchaseClear1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo mi_sales1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("New"),
    NULL,
    (gpointer) on_SalesNew1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Edit"),
    NULL,
    (gpointer) on_SalesEdit1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Save"),
    NULL,
    (gpointer) on_SalesSave1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("Clear"),
    NULL,
    (gpointer) on_SalesClear1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo menubar1_uiinfo[] =
{
  {
    GNOME_APP_UI_SUBTREE, N_("_File"),
    NULL,
    menuitem1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Edit"),
    NULL,
    edit_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Article"),
    NULL,
    mi_article1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Purchase"),
    NULL,
    mi_purchase1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Sales"),
    NULL,
    mi_sales1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

GtkWidget*
create_ArticlesMainwindow (void)
{
  GtkWidget *ArticlesMainwindow;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *toolbar1;
  GtkWidget *hbox1;
  GtkWidget *lFindNumber;
  GtkWidget *eFindNumber;
  GtkWidget *lFindDesignation;
  GtkWidget *eFindDesignation;
  GtkWidget *bSearch;
  GtkWidget *scrolledwindow1;
  GtkWidget *tree1;
  GtkWidget *notebook1;
  GtkWidget *fixed1;
  GtkWidget *table1;
  GtkWidget *eNumber;
  GtkWidget *eDesignation;
  GtkWidget *eUnit;
  GtkWidget *eWrapping;
  GtkWidget *eQuantumPerWrap;
  GtkWidget *lNumber;
  GtkWidget *lDesignation;
  GtkWidget *lUnit;
  GtkWidget *lWrapping;
  GtkWidget *lQuantumPerWrap;
  GtkWidget *label17;
  GtkWidget *vbox3;
  GtkWidget *hbox3;
  GtkWidget *label22;
  GtkWidget *ePurchaseDesignation;
  GtkWidget *tPrices;
  GtkWidget *lVendor;
  GtkWidget *lUnitPrice;
  GtkWidget *lDiscount;
  GtkWidget *lMiniQuantum;
  GtkWidget *label16;
  GtkWidget *eAddressField1;
  GtkWidget *eMinQuantum;
  GtkWidget *bChooseVendor;
  GtkWidget *eAddressNumber;
  GtkWidget *eUnitPrice;
  GtkWidget *eDiscount;
  GtkWidget *eMinquantum;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *eNrByVendor;
  GtkWidget *eDesignationByVendor;
  GtkWidget *label18;
  GtkWidget *vbox4;
  GtkWidget *hbox4;
  GtkWidget *label23;
  GtkWidget *eSellingDesignation;
  GtkWidget *tSales;
  GtkWidget *lSellingPrics1;
  GtkWidget *lSellingPrice2;
  GtkWidget *lSellingPrice3;
  GtkWidget *lSellingPrics4;
  GtkWidget *eSellingPrice1;
  GtkWidget *eSellingPrice2;
  GtkWidget *eSellingPrice3;
  GtkWidget *eSellingPrice4;
  GtkWidget *label24;
  GtkWidget *cbVat;
  GtkWidget *eVat;
  GtkWidget *label19;

  ArticlesMainwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ArticlesMainwindow), _("Articles"));

  vbox1 = gtk_vbox_new (FALSE, 17);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (ArticlesMainwindow), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);
  gnome_app_fill_menu (GTK_MENU_SHELL (menubar1), menubar1_uiinfo,
                       NULL, FALSE, 0);

  gtk_widget_set_sensitive (edit_menu_uiinfo[0].widget, FALSE);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);

  hbox1 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, FALSE, 0);

  lFindNumber = gtk_label_new (_("Number"));
  gtk_widget_show (lFindNumber);
  gtk_box_pack_start (GTK_BOX (hbox1), lFindNumber, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (lFindNumber), GTK_JUSTIFY_CENTER);

  eFindNumber = gtk_entry_new ();
  gtk_widget_show (eFindNumber);
  gtk_box_pack_start (GTK_BOX (hbox1), eFindNumber, FALSE, FALSE, 0);

  lFindDesignation = gtk_label_new (_("Designation"));
  gtk_widget_show (lFindDesignation);
  gtk_box_pack_start (GTK_BOX (hbox1), lFindDesignation, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (lFindDesignation), GTK_JUSTIFY_CENTER);

  eFindDesignation = gtk_entry_new ();
  gtk_widget_show (eFindDesignation);
  gtk_box_pack_start (GTK_BOX (hbox1), eFindDesignation, FALSE, FALSE, 0);

  bSearch = gtk_button_new_with_mnemonic (_("Search"));
  gtk_widget_show (bSearch);
  gtk_box_pack_start (GTK_BOX (hbox1), bSearch, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow1, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (scrolledwindow1, GTK_CAN_FOCUS);

  tree1 = gtk_tree_view_new ();
  gtk_widget_show (tree1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), tree1);
  gtk_widget_set_size_request (tree1, 185, 147);
  GTK_WIDGET_UNSET_FLAGS (tree1, GTK_CAN_FOCUS);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox1), notebook1, TRUE, TRUE, 0);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed1);

  table1 = gtk_table_new (5, 2, FALSE);
  gtk_widget_show (table1);
  gtk_fixed_put (GTK_FIXED (fixed1), table1, 8, 8);
  gtk_widget_set_size_request (table1, 547, 184);

  eNumber = gtk_entry_new ();
  gtk_widget_show (eNumber);
  gtk_table_attach (GTK_TABLE (table1), eNumber, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (eNumber, 0, 0);

  eDesignation = gtk_entry_new ();
  gtk_widget_show (eDesignation);
  gtk_table_attach (GTK_TABLE (table1), eDesignation, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (eDesignation, 0, 0);

  eUnit = gtk_entry_new ();
  gtk_widget_show (eUnit);
  gtk_table_attach (GTK_TABLE (table1), eUnit, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (eUnit, 0, 0);

  eWrapping = gtk_entry_new ();
  gtk_widget_show (eWrapping);
  gtk_table_attach (GTK_TABLE (table1), eWrapping, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (eWrapping, 0, 0);

  eQuantumPerWrap = gtk_entry_new ();
  gtk_widget_show (eQuantumPerWrap);
  gtk_table_attach (GTK_TABLE (table1), eQuantumPerWrap, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (eQuantumPerWrap, 0, 0);

  lNumber = gtk_label_new (_("Number"));
  gtk_widget_show (lNumber);
  gtk_table_attach (GTK_TABLE (table1), lNumber, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lNumber, 0, 0);

  lDesignation = gtk_label_new (_("Desig."));
  gtk_widget_show (lDesignation);
  gtk_table_attach (GTK_TABLE (table1), lDesignation, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lDesignation, 0, 0);
  gtk_label_set_justify (GTK_LABEL (lDesignation), GTK_JUSTIFY_CENTER);

  lUnit = gtk_label_new (_("Unit"));
  gtk_widget_show (lUnit);
  gtk_table_attach (GTK_TABLE (table1), lUnit, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lUnit, 0, 0);
  gtk_label_set_justify (GTK_LABEL (lUnit), GTK_JUSTIFY_CENTER);

  lWrapping = gtk_label_new (_("Wrapping"));
  gtk_widget_show (lWrapping);
  gtk_table_attach (GTK_TABLE (table1), lWrapping, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lWrapping, 0, 0);
  gtk_label_set_justify (GTK_LABEL (lWrapping), GTK_JUSTIFY_CENTER);

  lQuantumPerWrap = gtk_label_new (_("Qu. per Wrap."));
  gtk_widget_show (lQuantumPerWrap);
  gtk_table_attach (GTK_TABLE (table1), lQuantumPerWrap, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (lQuantumPerWrap, 0, 0);

  label17 = gtk_label_new (_("Article"));
  gtk_widget_show (label17);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label17);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox3);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox3, FALSE, FALSE, 0);

  label22 = gtk_label_new (_("Designation"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox3), label22, FALSE, FALSE, 0);

  ePurchaseDesignation = gtk_entry_new ();
  gtk_widget_show (ePurchaseDesignation);
  gtk_box_pack_start (GTK_BOX (hbox3), ePurchaseDesignation, TRUE, TRUE, 0);

  tPrices = gtk_table_new (5, 4, FALSE);
  gtk_widget_show (tPrices);
  gtk_box_pack_start (GTK_BOX (vbox3), tPrices, TRUE, TRUE, 0);

  lVendor = gtk_label_new (_("Vendor "));
  gtk_widget_show (lVendor);
  gtk_table_attach (GTK_TABLE (tPrices), lVendor, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lVendor), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lVendor), 0, 0.5);

  lUnitPrice = gtk_label_new (_("unit price "));
  gtk_widget_show (lUnitPrice);
  gtk_table_attach (GTK_TABLE (tPrices), lUnitPrice, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lUnitPrice), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lUnitPrice), 0, 0.5);

  lDiscount = gtk_label_new (_("Discount "));
  gtk_widget_show (lDiscount);
  gtk_table_attach (GTK_TABLE (tPrices), lDiscount, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lDiscount), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lDiscount), 0, 0.5);

  lMiniQuantum = gtk_label_new (_("min. Quant."));
  gtk_widget_show (lMiniQuantum);
  gtk_table_attach (GTK_TABLE (tPrices), lMiniQuantum, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lMiniQuantum), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lMiniQuantum), 0, 0.5);

  label16 = gtk_label_new (_("label16"));
  gtk_widget_show (label16);
  gtk_table_attach (GTK_TABLE (tPrices), label16, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label16), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label16), 0, 0.5);

  eAddressField1 = gtk_entry_new ();
  gtk_widget_show (eAddressField1);
  gtk_table_attach (GTK_TABLE (tPrices), eAddressField1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (eAddressField1), FALSE);

  eMinQuantum = gtk_entry_new ();
  gtk_widget_show (eMinQuantum);
  gtk_table_attach (GTK_TABLE (tPrices), eMinQuantum, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bChooseVendor = gtk_button_new_with_mnemonic (_("choose Vendor"));
  gtk_widget_show (bChooseVendor);
  gtk_table_attach (GTK_TABLE (tPrices), bChooseVendor, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  eAddressNumber = gtk_entry_new ();
  gtk_widget_show (eAddressNumber);
  gtk_table_attach (GTK_TABLE (tPrices), eAddressNumber, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  eUnitPrice = gtk_entry_new ();
  gtk_widget_show (eUnitPrice);
  gtk_table_attach (GTK_TABLE (tPrices), eUnitPrice, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  eDiscount = gtk_entry_new ();
  gtk_widget_show (eDiscount);
  gtk_table_attach (GTK_TABLE (tPrices), eDiscount, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  eMinquantum = gtk_entry_new ();
  gtk_widget_show (eMinquantum);
  gtk_table_attach (GTK_TABLE (tPrices), eMinquantum, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label20 = gtk_label_new (_("Nr. by Vendor"));
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (tPrices), label20, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  label21 = gtk_label_new (_("Des. by Vendor"));
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (tPrices), label21, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label21), 0, 0.5);

  eNrByVendor = gtk_entry_new ();
  gtk_widget_show (eNrByVendor);
  gtk_table_attach (GTK_TABLE (tPrices), eNrByVendor, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  eDesignationByVendor = gtk_entry_new ();
  gtk_widget_show (eDesignationByVendor);
  gtk_table_attach (GTK_TABLE (tPrices), eDesignationByVendor, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label18 = gtk_label_new (_("Purchase"));
  gtk_widget_show (label18);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label18);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox4);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox4, FALSE, FALSE, 0);

  label23 = gtk_label_new (_("Designation"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox4), label23, FALSE, FALSE, 0);

  eSellingDesignation = gtk_entry_new ();
  gtk_widget_show (eSellingDesignation);
  gtk_box_pack_start (GTK_BOX (hbox4), eSellingDesignation, TRUE, TRUE, 0);

  tSales = gtk_table_new (4, 4, FALSE);
  gtk_widget_show (tSales);
  gtk_box_pack_start (GTK_BOX (vbox4), tSales, TRUE, TRUE, 0);

  lSellingPrics1 = gtk_label_new (_("Selling-Price I"));
  gtk_widget_show (lSellingPrics1);
  gtk_table_attach (GTK_TABLE (tSales), lSellingPrics1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lSellingPrics1), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lSellingPrics1), 0, 0.5);

  lSellingPrice2 = gtk_label_new (_("Selling-Price II"));
  gtk_widget_show (lSellingPrice2);
  gtk_table_attach (GTK_TABLE (tSales), lSellingPrice2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lSellingPrice2), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lSellingPrice2), 0, 0.5);

  lSellingPrice3 = gtk_label_new (_("Selling-Price III"));
  gtk_widget_show (lSellingPrice3);
  gtk_table_attach (GTK_TABLE (tSales), lSellingPrice3, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lSellingPrice3), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lSellingPrice3), 0, 0.5);

  lSellingPrics4 = gtk_label_new (_("Selling-Price IV"));
  gtk_widget_show (lSellingPrics4);
  gtk_table_attach (GTK_TABLE (tSales), lSellingPrics4, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lSellingPrics4), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (lSellingPrics4), 0, 0.5);

  eSellingPrice1 = gtk_entry_new ();
  gtk_widget_show (eSellingPrice1);
  gtk_table_attach (GTK_TABLE (tSales), eSellingPrice1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  eSellingPrice2 = gtk_entry_new ();
  gtk_widget_show (eSellingPrice2);
  gtk_table_attach (GTK_TABLE (tSales), eSellingPrice2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  eSellingPrice3 = gtk_entry_new ();
  gtk_widget_show (eSellingPrice3);
  gtk_table_attach (GTK_TABLE (tSales), eSellingPrice3, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  eSellingPrice4 = gtk_entry_new ();
  gtk_widget_show (eSellingPrice4);
  gtk_table_attach (GTK_TABLE (tSales), eSellingPrice4, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label24 = gtk_label_new (_("Vat"));
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (tSales), label24, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  cbVat = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (cbVat)->popwin),
                     "GladeParentKey", cbVat);
  gtk_widget_show (cbVat);
  gtk_table_attach (GTK_TABLE (tSales), cbVat, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  eVat = GTK_COMBO (cbVat)->entry;
  gtk_widget_show (eVat);

  label19 = gtk_label_new (_("Sale"));
  gtk_widget_show (label19);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label19);

  g_signal_connect ((gpointer) bSearch, "clicked",
                    G_CALLBACK (on_bSearch_clicked),
                    NULL);
  g_signal_connect ((gpointer) notebook1, "switch_page",
                    G_CALLBACK (on_notebook1_switch_page),
                    NULL);
  g_signal_connect ((gpointer) bChooseVendor, "clicked",
                    G_CALLBACK (on_bChooseVendor_clicked),
                    NULL);
  g_signal_connect ((gpointer) eAddressNumber, "changed",
                    G_CALLBACK (on_eAddressNumber_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ArticlesMainwindow, ArticlesMainwindow, "ArticlesMainwindow");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, menubar1_uiinfo[0].widget, "menuitem1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, menuitem1_menu_uiinfo[0].widget, "menuitem2");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, menuitem1_menu_uiinfo[1].widget, "menuitem3");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, menuitem1_menu_uiinfo[2].widget, "quit1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, menubar1_uiinfo[1].widget, "edit");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, edit_menu_uiinfo[0].widget, "chooseArticle");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, menubar1_uiinfo[2].widget, "mi_article1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, mi_article1_menu_uiinfo[0].widget, "new1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, mi_article1_menu_uiinfo[1].widget, "edit1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, mi_article1_menu_uiinfo[2].widget, "save1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, mi_article1_menu_uiinfo[3].widget, "menuitem5");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, mi_article1_menu_uiinfo[4].widget, "print1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, mi_article1_menu_uiinfo[5].widget, "menuitem6");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, mi_article1_menu_uiinfo[6].widget, "clear1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, menubar1_uiinfo[3].widget, "mi_purchase1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, mi_purchase1_menu_uiinfo[0].widget, "PurchaseNew1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, mi_purchase1_menu_uiinfo[1].widget, "PurchaseEdit1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, mi_purchase1_menu_uiinfo[2].widget, "PurchaseSave1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, mi_purchase1_menu_uiinfo[3].widget, "menuitem8");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, mi_purchase1_menu_uiinfo[4].widget, "PurchaseClear1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, menubar1_uiinfo[4].widget, "mi_sales1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, mi_sales1_menu_uiinfo[0].widget, "SalesNew1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, mi_sales1_menu_uiinfo[1].widget, "SalesEdit1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, mi_sales1_menu_uiinfo[2].widget, "SalesSave1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, mi_sales1_menu_uiinfo[3].widget, "separator1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, mi_sales1_menu_uiinfo[4].widget, "SalesClear1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, lFindNumber, "lFindNumber");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, eFindNumber, "eFindNumber");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, lFindDesignation, "lFindDesignation");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, eFindDesignation, "eFindDesignation");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, bSearch, "bSearch");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, tree1, "tree1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, table1, "table1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, eNumber, "eNumber");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, eDesignation, "eDesignation");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, eUnit, "eUnit");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, eWrapping, "eWrapping");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, eQuantumPerWrap, "eQuantumPerWrap");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, lNumber, "lNumber");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, lDesignation, "lDesignation");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, lUnit, "lUnit");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, lWrapping, "lWrapping");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, lQuantumPerWrap, "lQuantumPerWrap");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, label17, "label17");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, label22, "label22");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, ePurchaseDesignation, "ePurchaseDesignation");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, tPrices, "tPrices");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, lVendor, "lVendor");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, lUnitPrice, "lUnitPrice");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, lDiscount, "lDiscount");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, lMiniQuantum, "lMiniQuantum");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, label16, "label16");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, eAddressField1, "eAddressField1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, eMinQuantum, "eMinQuantum");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, bChooseVendor, "bChooseVendor");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, eAddressNumber, "eAddressNumber");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, eUnitPrice, "eUnitPrice");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, eDiscount, "eDiscount");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, eMinquantum, "eMinquantum");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, label20, "label20");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, label21, "label21");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, eNrByVendor, "eNrByVendor");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, eDesignationByVendor, "eDesignationByVendor");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, label18, "label18");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, label23, "label23");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, eSellingDesignation, "eSellingDesignation");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, tSales, "tSales");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, lSellingPrics1, "lSellingPrics1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, lSellingPrice2, "lSellingPrice2");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, lSellingPrice3, "lSellingPrice3");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, lSellingPrics4, "lSellingPrics4");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, eSellingPrice1, "eSellingPrice1");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, eSellingPrice2, "eSellingPrice2");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, eSellingPrice3, "eSellingPrice3");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, eSellingPrice4, "eSellingPrice4");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, label24, "label24");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, cbVat, "cbVat");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, eVat, "eVat");
  GLADE_HOOKUP_OBJECT (ArticlesMainwindow, label19, "label19");

  return ArticlesMainwindow;
}

