/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Login into Database");
gchar *s = N_("Username");
gchar *s = N_("Password");
gchar *s = N_("*");
gchar *s = N_("*");
