/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

static GnomeUIInfo file1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Print S_etup..."),
    NULL,
    (gpointer) on_choosePrinter1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_EXIT_ITEM (on_quit1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo bank1_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_NEW_ITEM (N_("_New"), NULL, on_new1_activate, NULL),
  {
    GNOME_APP_UI_ITEM, N_("_Edit"),
    NULL,
    (gpointer) on_edit1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_MENU_SAVE_ITEM (on_save1_activate, NULL),
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_PRINT_ITEM (on_print1_activate, NULL),
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_CLEAR_ITEM (on_delete1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo menubar1_uiinfo[] =
{
  {
    GNOME_APP_UI_SUBTREE, N_("_File"),
    NULL,
    file1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Bank"),
    NULL,
    bank1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

GtkWidget*
create_BankMainwindow (void)
{
  GtkWidget *BankMainwindow;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *toolitem1;
  GtkWidget *bChooseClient;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *lFindNumber;
  GtkWidget *eFindName;
  GtkWidget *lFindDesignation;
  GtkWidget *eFindCity;
  GtkWidget *bSearch;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *tree1;
  GtkWidget *notebook1;
  GtkWidget *vbox2;
  GtkWidget *table1;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *scrolledwindow3;
  GtkWidget *tvAddress;
  GtkWidget *hbox2;
  GtkWidget *eAddressID;
  GtkWidget *hbox4;
  GtkWidget *bChooseAddressOfBank;
  GtkWidget *label29;
  GtkWidget *eBCN;
  GtkWidget *label16;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  BankMainwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (BankMainwindow), _("Bank"));

  vbox1 = gtk_vbox_new (FALSE, 17);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (BankMainwindow), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);
  gnome_app_fill_menu (GTK_MENU_SHELL (menubar1), menubar1_uiinfo,
                       accel_group, FALSE, 0);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  toolitem1 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem1);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolitem1);

  bChooseClient = gtk_button_new ();
  gtk_widget_show (bChooseClient);
  gtk_container_add (GTK_CONTAINER (toolitem1), bChooseClient);
  gtk_widget_add_accelerator (bChooseClient, "clicked", accel_group,
                              GDK_A, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (bChooseClient), alignment1);

  hbox1 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, FALSE, 0);

  lFindNumber = gtk_label_new (_("Number"));
  gtk_widget_show (lFindNumber);
  gtk_box_pack_start (GTK_BOX (hbox1), lFindNumber, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (lFindNumber), GTK_JUSTIFY_CENTER);

  eFindName = gtk_entry_new ();
  gtk_widget_show (eFindName);
  gtk_box_pack_start (GTK_BOX (hbox1), eFindName, FALSE, FALSE, 0);

  lFindDesignation = gtk_label_new (_("Designation"));
  gtk_widget_show (lFindDesignation);
  gtk_box_pack_start (GTK_BOX (hbox1), lFindDesignation, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (lFindDesignation), GTK_JUSTIFY_CENTER);

  eFindCity = gtk_entry_new ();
  gtk_widget_show (eFindCity);
  gtk_box_pack_start (GTK_BOX (hbox1), eFindCity, FALSE, FALSE, 0);

  bSearch = gtk_button_new_with_mnemonic (_("Search"));
  gtk_widget_show (bSearch);
  gtk_box_pack_start (GTK_BOX (hbox1), bSearch, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow1, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (scrolledwindow1, GTK_CAN_FOCUS);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);

  tree1 = gtk_tree_view_new ();
  gtk_widget_show (tree1);
  gtk_container_add (GTK_CONTAINER (viewport1), tree1);
  GTK_WIDGET_UNSET_FLAGS (tree1, GTK_CAN_FOCUS);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox1), notebook1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (notebook1), 1);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox2);

  table1 = gtk_table_new (4, 3, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox2), table1, TRUE, TRUE, 0);

  label18 = gtk_label_new (_("Address"));
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (table1), label18, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0.5);

  label19 = gtk_label_new (_("Bank Code Nr. "));
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (table1), label19, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0.5);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_table_attach (GTK_TABLE (table1), scrolledwindow3, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_SHADOW_IN);

  tvAddress = gtk_text_view_new ();
  gtk_widget_show (tvAddress);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), tvAddress);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (tvAddress), FALSE);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_table_attach (GTK_TABLE (table1), hbox2, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  eAddressID = gtk_entry_new ();
  gtk_widget_show (eAddressID);
  gtk_box_pack_start (GTK_BOX (hbox2), eAddressID, FALSE, FALSE, 0);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (hbox2), hbox4, TRUE, TRUE, 0);

  bChooseAddressOfBank = gtk_button_new_with_mnemonic (_("choose Address"));
  gtk_widget_show (bChooseAddressOfBank);
  gtk_box_pack_start (GTK_BOX (hbox4), bChooseAddressOfBank, FALSE, FALSE, 0);

  label29 = gtk_label_new (_("Bank"));
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (table1), label29, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label29), 0, 0.5);

  eBCN = gtk_entry_new ();
  gtk_widget_show (eBCN);
  gtk_table_attach (GTK_TABLE (table1), eBCN, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label16 = gtk_label_new (_("Bank"));
  gtk_widget_show (label16);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label16);

  g_signal_connect ((gpointer) bChooseClient, "clicked",
                    G_CALLBACK (on_bChooseClient_clicked),
                    NULL);
  g_signal_connect ((gpointer) bSearch, "clicked",
                    G_CALLBACK (on_bSearch_clicked),
                    NULL);
  g_signal_connect ((gpointer) tree1, "row_activated",
                    G_CALLBACK (on_tree1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) eAddressID, "changed",
                    G_CALLBACK (on_eAddressID_changed),
                    NULL);
  g_signal_connect ((gpointer) bChooseAddressOfBank, "clicked",
                    G_CALLBACK (on_bChooseAddressOfBank_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (BankMainwindow, BankMainwindow, "BankMainwindow");
  GLADE_HOOKUP_OBJECT (BankMainwindow, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (BankMainwindow, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (BankMainwindow, menubar1_uiinfo[0].widget, "file1");
  GLADE_HOOKUP_OBJECT (BankMainwindow, file1_menu_uiinfo[0].widget, "choosePrinter1");
  GLADE_HOOKUP_OBJECT (BankMainwindow, file1_menu_uiinfo[1].widget, "separator2");
  GLADE_HOOKUP_OBJECT (BankMainwindow, file1_menu_uiinfo[2].widget, "quit1");
  GLADE_HOOKUP_OBJECT (BankMainwindow, menubar1_uiinfo[1].widget, "bank1");
  GLADE_HOOKUP_OBJECT (BankMainwindow, bank1_menu_uiinfo[0].widget, "new1");
  GLADE_HOOKUP_OBJECT (BankMainwindow, bank1_menu_uiinfo[1].widget, "edit1");
  GLADE_HOOKUP_OBJECT (BankMainwindow, bank1_menu_uiinfo[2].widget, "save1");
  GLADE_HOOKUP_OBJECT (BankMainwindow, bank1_menu_uiinfo[3].widget, "separator3");
  GLADE_HOOKUP_OBJECT (BankMainwindow, bank1_menu_uiinfo[4].widget, "print1");
  GLADE_HOOKUP_OBJECT (BankMainwindow, bank1_menu_uiinfo[5].widget, "separator1");
  GLADE_HOOKUP_OBJECT (BankMainwindow, bank1_menu_uiinfo[6].widget, "delete1");
  GLADE_HOOKUP_OBJECT (BankMainwindow, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (BankMainwindow, toolitem1, "toolitem1");
  GLADE_HOOKUP_OBJECT (BankMainwindow, bChooseClient, "bChooseClient");
  GLADE_HOOKUP_OBJECT (BankMainwindow, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (BankMainwindow, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (BankMainwindow, lFindNumber, "lFindNumber");
  GLADE_HOOKUP_OBJECT (BankMainwindow, eFindName, "eFindName");
  GLADE_HOOKUP_OBJECT (BankMainwindow, lFindDesignation, "lFindDesignation");
  GLADE_HOOKUP_OBJECT (BankMainwindow, eFindCity, "eFindCity");
  GLADE_HOOKUP_OBJECT (BankMainwindow, bSearch, "bSearch");
  GLADE_HOOKUP_OBJECT (BankMainwindow, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (BankMainwindow, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (BankMainwindow, tree1, "tree1");
  GLADE_HOOKUP_OBJECT (BankMainwindow, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (BankMainwindow, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (BankMainwindow, table1, "table1");
  GLADE_HOOKUP_OBJECT (BankMainwindow, label18, "label18");
  GLADE_HOOKUP_OBJECT (BankMainwindow, label19, "label19");
  GLADE_HOOKUP_OBJECT (BankMainwindow, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (BankMainwindow, tvAddress, "tvAddress");
  GLADE_HOOKUP_OBJECT (BankMainwindow, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (BankMainwindow, eAddressID, "eAddressID");
  GLADE_HOOKUP_OBJECT (BankMainwindow, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (BankMainwindow, bChooseAddressOfBank, "bChooseAddressOfBank");
  GLADE_HOOKUP_OBJECT (BankMainwindow, label29, "label29");
  GLADE_HOOKUP_OBJECT (BankMainwindow, eBCN, "eBCN");
  GLADE_HOOKUP_OBJECT (BankMainwindow, label16, "label16");

  gtk_window_add_accel_group (GTK_WINDOW (BankMainwindow), accel_group);

  return BankMainwindow;
}

