#! /bin/sh
#
# skeleton	Example initscript
#		This file should be used to construct scripts to be
#		placed in /etc/init.d.
#
# Author:	Miquel van Smoorenburg <miquels@cistron.nl>.
#		Ian Murdock <imurdock@gnu.ai.mit.edu>.
#
#		Please remove the "Author" lines above and replace them
#		with your own name if you copy and modify this script.
#
# Version:	@(#)skeleton  2.85-23  28-Jul-2004  miquels@cistron.nl
#


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/share/cuon/cuon_server/src
DESC="some daemon"
NAME=server_report.py
DAEMON=/usr/share/cuon/cuon_server/src/$NAME
PIDFILE=/var/run/cuon_server_report.pid
SCRIPTNAME=/etc/init.d/$NAME

# Gracefully exit if the package has been removed.
#test -x $DAEMON || echo "Not found\n" ;  exit 0

# Read config file if it is present.
#if [ -r /etc/default/$NAME ]
#then
#	. /etc/default/$NAME
#fi

#
#	Function that starts the daemon/service.
#
d_start() {
	nohup start-stop-daemon --start  --quiet  --exec $DAEMON  &
   nohup start-stop-daemon --start python --exec $DAEMON 1>>/var/log/cuonreport.log 2>>/var/log/cuonreport_err.log &
   
                   
}

#
#	Function that stops the daemon/service.
#
d_stop() {
    OLDPID=`ps ax | grep $NAME | grep -v grep | sed  -e "s/^[[:space:]]*//g" | cut -d" " -f 1 `
    if [ -n "$OLDPID" ] 
    then 
        kill `ps ax | grep $NAME | grep -v grep | sed  -e "s/^[[:space:]]*//g" | cut -d" " -f 1 `
    fi
  }

#
#	Function that sends a SIGHUP to the daemon/service.
#
d_reload() {
	start-stop-daemon --stop --quiet --pidfile $PIDFILE \
		--name $NAME --signal 1
}

case "$1" in
  start)
	echo  "Starting $DESC: $NAME"
	d_start
  
	;;
  stop)
	echo -n "Stopping $DESC: $NAME"
	d_stop
  echo "."
	;;
  #reload)
	#
	#	If the daemon can reload its configuration without
	#	restarting (for example, when it is sent a SIGHUP),
	#	then implement that here.
	#
	#	If the daemon responds to changes in its config file
	#	directly anyway, make this an "exit 0".
	#
	# echo -n "Reloading $DESC configuration..."
	# d_reload
	# echo "done."
  #;;
  restart|force-reload)
	#
	#	If the "reload" option is implemented, move the "force-reload"
	#	option to the "reload" entry above. If not, "force-reload" is
	#	just the same as "restart".
	#
	echo -n "Restarting $DESC: $NAME"
	d_stop
	sleep 1
	d_start
	echo "."
	;;
  *)
	# echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac
function CheckPid()
{
echo ps -a -o pid,cmd | grep $NAME | egrep ^[[:space:]]
}
exit 0
