/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

static GnomeUIInfo file1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Print S_etup..."),
    NULL,
    (gpointer) on_choosePrinter1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_CLOSE_ITEM (on_quit1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo profile1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("New "),
    NULL,
    (gpointer) on_new1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Edit"),
    NULL,
    (gpointer) on_edit1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Save"),
    NULL,
    (gpointer) on_save1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("print"),
    NULL,
    (gpointer) on_print1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("clear"),
    NULL,
    (gpointer) on_clear1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo menubar1_uiinfo[] =
{
  {
    GNOME_APP_UI_SUBTREE, N_("_File"),
    NULL,
    file1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Profile"),
    NULL,
    profile1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

GtkWidget*
create_PreferencesMainwindow (void)
{
  GtkWidget *PreferencesMainwindow;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *toolbar1;
  GtkWidget *hbox1;
  GtkWidget *lFindName;
  GtkWidget *eFindname;
  GtkWidget *lFindDescription;
  GtkWidget *eFindDescription;
  GtkWidget *button1;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *tree1;
  GtkWidget *notebook1;
  GtkWidget *fixed3;
  GtkWidget *eProfileName;
  GtkWidget *eProfileDescription;
  GtkWidget *label2;
  GtkWidget *label1;
  GtkWidget *eSqlEncoding;
  GtkWidget *label7;
  GtkWidget *eLocales;
  GtkWidget *label13;
  GtkWidget *chbStandardProfile;
  GtkWidget *lProfile;
  GtkWidget *fixed1;
  GtkWidget *label8;
  GtkWidget *combo1;
  GList *combo1_items = NULL;
  GtkWidget *cbPrintSystem;
  GtkWidget *label4;
  GtkWidget *table1;
  GtkWidget *fileentry2;
  GtkWidget *cbPath_Report_Invoice;
  GtkWidget *fileentry3;
  GtkWidget *cbPath_Report_Addresslists;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *fileentry6;
  GtkWidget *cbPath_Report_Supply;
  GtkWidget *fileentry7;
  GtkWidget *cbPath_Report_Pickup;
  GtkWidget *label5;
  GtkWidget *table2;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *fileentry4;
  GtkWidget *cbPath_Docs_Addresslists;
  GtkWidget *fileentry5;
  GtkWidget *cbPath_Docs_Invoices;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *fileentry8;
  GtkWidget *cbPath_Docs_Supply;
  GtkWidget *fileentry9;
  GtkWidget *cbPath_Docs_Pickup;
  GtkWidget *label6;

  PreferencesMainwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (PreferencesMainwindow), _("Preferences"));

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (PreferencesMainwindow), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);
  gnome_app_fill_menu (GTK_MENU_SHELL (menubar1), menubar1_uiinfo,
                       NULL, FALSE, 0);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);

  hbox1 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, TRUE, 0);

  lFindName = gtk_label_new (_("Name1"));
  gtk_widget_show (lFindName);
  gtk_box_pack_start (GTK_BOX (hbox1), lFindName, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (lFindName), GTK_JUSTIFY_CENTER);

  eFindname = gtk_entry_new ();
  gtk_widget_show (eFindname);
  gtk_box_pack_start (GTK_BOX (hbox1), eFindname, FALSE, FALSE, 0);

  lFindDescription = gtk_label_new (_("Descript."));
  gtk_widget_show (lFindDescription);
  gtk_box_pack_start (GTK_BOX (hbox1), lFindDescription, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (lFindDescription), GTK_JUSTIFY_CENTER);

  eFindDescription = gtk_entry_new ();
  gtk_widget_show (eFindDescription);
  gtk_box_pack_start (GTK_BOX (hbox1), eFindDescription, FALSE, FALSE, 0);

  button1 = gtk_button_new_with_mnemonic (_("Search"));
  gtk_widget_show (button1);
  gtk_box_pack_start (GTK_BOX (hbox1), button1, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow1, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (scrolledwindow1, GTK_CAN_FOCUS);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);

  tree1 = gtk_tree_view_new ();
  gtk_widget_show (tree1);
  gtk_container_add (GTK_CONTAINER (viewport1), tree1);
  GTK_WIDGET_UNSET_FLAGS (tree1, GTK_CAN_FOCUS);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox1), notebook1, TRUE, TRUE, 0);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  eProfileName = gtk_entry_new ();
  gtk_widget_show (eProfileName);
  gtk_fixed_put (GTK_FIXED (fixed3), eProfileName, 128, 8);
  gtk_widget_set_size_request (eProfileName, 0, 0);

  eProfileDescription = gtk_entry_new ();
  gtk_widget_show (eProfileDescription);
  gtk_fixed_put (GTK_FIXED (fixed3), eProfileDescription, 128, 56);
  gtk_widget_set_size_request (eProfileDescription, 0, 0);

  label2 = gtk_label_new (_("Description"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed3), label2, 0, 56);
  gtk_widget_set_size_request (label2, 0, 0);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_CENTER);

  label1 = gtk_label_new (_("Name"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed3), label1, 8, 8);
  gtk_widget_set_size_request (label1, 0, 0);

  eSqlEncoding = gtk_entry_new ();
  gtk_widget_show (eSqlEncoding);
  gtk_fixed_put (GTK_FIXED (fixed3), eSqlEncoding, 536, 16);
  gtk_widget_set_size_request (eSqlEncoding, 158, 31);
  gtk_entry_set_width_chars (GTK_ENTRY (eSqlEncoding), 20);

  label7 = gtk_label_new (_("SQL-Encoding"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed3), label7, 344, 16);
  gtk_widget_set_size_request (label7, 0, 0);

  eLocales = gtk_entry_new ();
  gtk_widget_show (eLocales);
  gtk_fixed_put (GTK_FIXED (fixed3), eLocales, 536, 56);
  gtk_widget_set_size_request (eLocales, 158, 31);

  label13 = gtk_label_new (_("Locales"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 344, 56);
  gtk_widget_set_size_request (label13, 0, 0);

  chbStandardProfile = gtk_check_button_new_with_mnemonic (_("standard Profile"));
  gtk_widget_show (chbStandardProfile);
  gtk_fixed_put (GTK_FIXED (fixed3), chbStandardProfile, 0, 120);
  gtk_widget_set_size_request (chbStandardProfile, 0, 0);

  lProfile = gtk_label_new (_("Profile"));
  gtk_widget_show (lProfile);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), lProfile);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed1);

  label8 = gtk_label_new (_("Print-System"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed1), label8, 8, 8);
  gtk_widget_set_size_request (label8, 0, 0);

  combo1 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo1)->popwin),
                     "GladeParentKey", combo1);
  gtk_widget_show (combo1);
  gtk_fixed_put (GTK_FIXED (fixed1), combo1, 169, 10);
  gtk_widget_set_size_request (combo1, 185, 31);
  combo1_items = g_list_append (combo1_items, (gpointer) _("GTKLP"));
  combo1_items = g_list_append (combo1_items, (gpointer) _("CUPS"));
  combo1_items = g_list_append (combo1_items, (gpointer) _("LPR"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo1), combo1_items);
  g_list_free (combo1_items);

  cbPrintSystem = GTK_COMBO (combo1)->entry;
  gtk_widget_show (cbPrintSystem);

  label4 = gtk_label_new (_("Printing-System"));
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label4);

  table1 = gtk_table_new (6, 4, FALSE);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (notebook1), table1);

  fileentry2 = gnome_file_entry_new (NULL, NULL);
  gtk_widget_show (fileentry2);
  gtk_table_attach (GTK_TABLE (table1), fileentry2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (fileentry2, 0, 0);
  gnome_file_entry_set_directory_entry (GNOME_FILE_ENTRY (fileentry2), TRUE);

  cbPath_Report_Invoice = gnome_file_entry_gtk_entry (GNOME_FILE_ENTRY (fileentry2));
  gtk_widget_show (cbPath_Report_Invoice);

  fileentry3 = gnome_file_entry_new (NULL, NULL);
  gtk_widget_show (fileentry3);
  gtk_table_attach (GTK_TABLE (table1), fileentry3, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gnome_file_entry_set_directory_entry (GNOME_FILE_ENTRY (fileentry3), TRUE);

  cbPath_Report_Addresslists = gnome_file_entry_gtk_entry (GNOME_FILE_ENTRY (fileentry3));
  gtk_widget_show (cbPath_Report_Addresslists);

  label9 = gtk_label_new (_("Path to Addresslists"));
  gtk_widget_show (label9);
  gtk_table_attach (GTK_TABLE (table1), label9, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label9), 0, 0.5);

  label10 = gtk_label_new (_("Path to Invoices"));
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table1), label10, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label10), 0, 0.5);

  label14 = gtk_label_new (_("Path to Supply"));
  gtk_widget_show (label14);
  gtk_table_attach (GTK_TABLE (table1), label14, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);

  label15 = gtk_label_new (_("Path to Pickup"));
  gtk_widget_show (label15);
  gtk_table_attach (GTK_TABLE (table1), label15, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label15), 0, 0.5);

  fileentry6 = gnome_file_entry_new (NULL, NULL);
  gtk_widget_show (fileentry6);
  gtk_table_attach (GTK_TABLE (table1), fileentry6, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gnome_file_entry_set_directory_entry (GNOME_FILE_ENTRY (fileentry6), TRUE);

  cbPath_Report_Supply = gnome_file_entry_gtk_entry (GNOME_FILE_ENTRY (fileentry6));
  gtk_widget_show (cbPath_Report_Supply);

  fileentry7 = gnome_file_entry_new (NULL, NULL);
  gtk_widget_show (fileentry7);
  gtk_table_attach (GTK_TABLE (table1), fileentry7, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gnome_file_entry_set_directory_entry (GNOME_FILE_ENTRY (fileentry7), TRUE);

  cbPath_Report_Pickup = gnome_file_entry_gtk_entry (GNOME_FILE_ENTRY (fileentry7));
  gtk_widget_show (cbPath_Report_Pickup);

  label5 = gtk_label_new (_("Path to Reports"));
  gtk_widget_show (label5);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label5);

  table2 = gtk_table_new (6, 4, FALSE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (notebook1), table2);

  label11 = gtk_label_new (_("Path to Addresslists"));
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (table2), label11, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label11), 0, 0.5);

  label12 = gtk_label_new (_("Path to Invoices"));
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table2), label12, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label12), 0, 0.5);

  fileentry4 = gnome_file_entry_new (NULL, NULL);
  gtk_widget_show (fileentry4);
  gtk_table_attach (GTK_TABLE (table2), fileentry4, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gnome_file_entry_set_directory_entry (GNOME_FILE_ENTRY (fileentry4), TRUE);

  cbPath_Docs_Addresslists = gnome_file_entry_gtk_entry (GNOME_FILE_ENTRY (fileentry4));
  gtk_widget_show (cbPath_Docs_Addresslists);

  fileentry5 = gnome_file_entry_new (NULL, NULL);
  gtk_widget_show (fileentry5);
  gtk_table_attach (GTK_TABLE (table2), fileentry5, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gnome_file_entry_set_directory_entry (GNOME_FILE_ENTRY (fileentry5), TRUE);

  cbPath_Docs_Invoices = gnome_file_entry_gtk_entry (GNOME_FILE_ENTRY (fileentry5));
  gtk_widget_show (cbPath_Docs_Invoices);

  label16 = gtk_label_new (_("Path to Supply"));
  gtk_widget_show (label16);
  gtk_table_attach (GTK_TABLE (table2), label16, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label16), 0, 0.5);

  label17 = gtk_label_new (_("Path to Pickup"));
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (table2), label17, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label17), 0, 0.5);

  fileentry8 = gnome_file_entry_new (NULL, NULL);
  gtk_widget_show (fileentry8);
  gtk_table_attach (GTK_TABLE (table2), fileentry8, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gnome_file_entry_set_directory_entry (GNOME_FILE_ENTRY (fileentry8), TRUE);

  cbPath_Docs_Supply = gnome_file_entry_gtk_entry (GNOME_FILE_ENTRY (fileentry8));
  gtk_widget_show (cbPath_Docs_Supply);

  fileentry9 = gnome_file_entry_new (NULL, NULL);
  gtk_widget_show (fileentry9);
  gtk_table_attach (GTK_TABLE (table2), fileentry9, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gnome_file_entry_set_directory_entry (GNOME_FILE_ENTRY (fileentry9), TRUE);

  cbPath_Docs_Pickup = gnome_file_entry_gtk_entry (GNOME_FILE_ENTRY (fileentry9));
  gtk_widget_show (cbPath_Docs_Pickup);

  label6 = gtk_label_new (_("Path to Doc`s"));
  gtk_widget_show (label6);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label6);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_bSearch_clicked),
                    NULL);
  g_signal_connect ((gpointer) notebook1, "switch_page",
                    G_CALLBACK (on_notebook1_switch_page),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (PreferencesMainwindow, PreferencesMainwindow, "PreferencesMainwindow");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, menubar1_uiinfo[0].widget, "file1");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, file1_menu_uiinfo[0].widget, "choosePrinter1");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, file1_menu_uiinfo[1].widget, "separator2");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, file1_menu_uiinfo[2].widget, "quit1");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, menubar1_uiinfo[1].widget, "profile1");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, profile1_menu_uiinfo[0].widget, "new1");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, profile1_menu_uiinfo[1].widget, "edit1");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, profile1_menu_uiinfo[2].widget, "save1");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, profile1_menu_uiinfo[3].widget, "separator3");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, profile1_menu_uiinfo[4].widget, "print1");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, profile1_menu_uiinfo[5].widget, "separator1");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, profile1_menu_uiinfo[6].widget, "clear1");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, lFindName, "lFindName");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, eFindname, "eFindname");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, lFindDescription, "lFindDescription");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, eFindDescription, "eFindDescription");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, button1, "button1");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, tree1, "tree1");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, eProfileName, "eProfileName");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, eProfileDescription, "eProfileDescription");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, label2, "label2");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, label1, "label1");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, eSqlEncoding, "eSqlEncoding");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, label7, "label7");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, eLocales, "eLocales");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, label13, "label13");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, chbStandardProfile, "chbStandardProfile");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, lProfile, "lProfile");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, label8, "label8");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, combo1, "combo1");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, cbPrintSystem, "cbPrintSystem");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, label4, "label4");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, table1, "table1");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, fileentry2, "fileentry2");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, cbPath_Report_Invoice, "cbPath_Report_Invoice");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, fileentry3, "fileentry3");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, cbPath_Report_Addresslists, "cbPath_Report_Addresslists");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, label9, "label9");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, label10, "label10");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, label14, "label14");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, label15, "label15");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, fileentry6, "fileentry6");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, cbPath_Report_Supply, "cbPath_Report_Supply");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, fileentry7, "fileentry7");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, cbPath_Report_Pickup, "cbPath_Report_Pickup");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, label5, "label5");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, table2, "table2");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, label11, "label11");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, label12, "label12");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, fileentry4, "fileentry4");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, cbPath_Docs_Addresslists, "cbPath_Docs_Addresslists");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, fileentry5, "fileentry5");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, cbPath_Docs_Invoices, "cbPath_Docs_Invoices");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, label16, "label16");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, label17, "label17");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, fileentry8, "fileentry8");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, cbPath_Docs_Supply, "cbPath_Docs_Supply");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, fileentry9, "fileentry9");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, cbPath_Docs_Pickup, "cbPath_Docs_Pickup");
  GLADE_HOOKUP_OBJECT (PreferencesMainwindow, label6, "label6");

  return PreferencesMainwindow;
}

