/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_UserID_Dialog (void)
{
  GtkWidget *UserID_Dialog;
  GtkWidget *dialog_vbox2;
  GtkWidget *table1;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *TUserID;
  GtkWidget *hbox5;
  GtkWidget *TPassword;
  GtkWidget *dialog_action_area2;
  GtkWidget *helpbutton1;
  GtkWidget *cancelbutton1;
  GtkWidget *okbutton1;

  UserID_Dialog = gtk_dialog_new ();
  gtk_container_set_border_width (GTK_CONTAINER (UserID_Dialog), 13);
  gtk_window_set_title (GTK_WINDOW (UserID_Dialog), _("Login into Database"));
  gtk_window_set_position (GTK_WINDOW (UserID_Dialog), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (UserID_Dialog), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (UserID_Dialog), FALSE);

  dialog_vbox2 = GTK_DIALOG (UserID_Dialog)->vbox;
  gtk_widget_show (dialog_vbox2);

  table1 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), table1, TRUE, TRUE, 0);

  label1 = gtk_label_new (_("Username"));
  gtk_widget_show (label1);
  gtk_table_attach (GTK_TABLE (table1), label1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_CENTER);

  label2 = gtk_label_new (_("Password"));
  gtk_widget_show (label2);
  gtk_table_attach (GTK_TABLE (table1), label2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_CENTER);

  TUserID = gtk_entry_new ();
  gtk_widget_show (TUserID);
  gtk_table_attach (GTK_TABLE (table1), TUserID, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_max_length (GTK_ENTRY (TUserID), 15);
  gtk_entry_set_activates_default (GTK_ENTRY (TUserID), TRUE);

  hbox5 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox5);
  gtk_table_attach (GTK_TABLE (table1), hbox5, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox5), 2);

  TPassword = gtk_entry_new ();
  gtk_widget_show (TPassword);
  gtk_box_pack_start (GTK_BOX (hbox5), TPassword, TRUE, TRUE, 0);
  gtk_entry_set_max_length (GTK_ENTRY (TPassword), 15);
  gtk_entry_set_visibility (GTK_ENTRY (TPassword), FALSE);
  gtk_entry_set_activates_default (GTK_ENTRY (TPassword), TRUE);

  dialog_action_area2 = GTK_DIALOG (UserID_Dialog)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  helpbutton1 = gtk_button_new_from_stock ("gtk-help");
  gtk_widget_show (helpbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (UserID_Dialog), helpbutton1, GTK_RESPONSE_HELP);
  GTK_WIDGET_SET_FLAGS (helpbutton1, GTK_CAN_DEFAULT);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (UserID_Dialog), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (UserID_Dialog), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) cancelbutton1, "clicked",
                    G_CALLBACK (on_cancelbutton1_clicked),
                    NULL);
  g_signal_connect ((gpointer) okbutton1, "clicked",
                    G_CALLBACK (on_okbutton1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (UserID_Dialog, UserID_Dialog, "UserID_Dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (UserID_Dialog, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (UserID_Dialog, table1, "table1");
  GLADE_HOOKUP_OBJECT (UserID_Dialog, label1, "label1");
  GLADE_HOOKUP_OBJECT (UserID_Dialog, label2, "label2");
  GLADE_HOOKUP_OBJECT (UserID_Dialog, TUserID, "TUserID");
  GLADE_HOOKUP_OBJECT (UserID_Dialog, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (UserID_Dialog, TPassword, "TPassword");
  GLADE_HOOKUP_OBJECT_NO_REF (UserID_Dialog, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (UserID_Dialog, helpbutton1, "helpbutton1");
  GLADE_HOOKUP_OBJECT (UserID_Dialog, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (UserID_Dialog, okbutton1, "okbutton1");

  return UserID_Dialog;
}

