/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

static GnomeUIInfo print1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Invoice"),
    NULL,
    (gpointer) on_print_invoice1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Delivery Note"),
    NULL,
    (gpointer) on_print_delivery_note1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Pickup Note"),
    NULL,
    (gpointer) on_print_pickup_note1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo file1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Print S_etup"),
    NULL,
    (gpointer) on_print_setup1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("_Print"),
    NULL,
    print1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("_Close"),
    NULL,
    (gpointer) on_quit1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo order1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("_New"),
    N_("New Order"),
    (gpointer) on_new1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("_Edit"),
    NULL,
    (gpointer) on_edit1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("_Save"),
    NULL,
    (gpointer) on_save1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("c_lear"),
    NULL,
    (gpointer) on_delete1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo supply1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("New"),
    NULL,
    (gpointer) on_SupplyNew1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Edit"),
    NULL,
    (gpointer) on_SupplyEdit1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("Save"),
    NULL,
    (gpointer) on_SupplySave1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("Clear"),
    NULL,
    (gpointer) on_SupplyDelete1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo gets1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("New"),
    NULL,
    (gpointer) on_GetsNew1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Edit"),
    NULL,
    (gpointer) on_GetsEdit1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("Save"),
    NULL,
    (gpointer) on_GetsSave1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("Clear"),
    NULL,
    (gpointer) on_GetsDelete1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo position1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("_New"),
    NULL,
    (gpointer) on_PositionNew1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("_Edit"),
    NULL,
    (gpointer) on_PositionEdit1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("_Save"),
    NULL,
    (gpointer) on_PositionSave1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("_Print"),
    NULL,
    (gpointer) on_PositionPrint1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("c_lear"),
    NULL,
    (gpointer) on_PositionDelete1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo menubar1_uiinfo[] =
{
  {
    GNOME_APP_UI_SUBTREE, N_("_File"),
    NULL,
    file1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Order"),
    N_("Manage Order"),
    order1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Supply"),
    NULL,
    supply1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Gets"),
    NULL,
    gets1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Position"),
    NULL,
    position1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

GtkWidget*
create_OrderMainwindow (void)
{
  GtkWidget *OrderMainwindow;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *toolbar1;
  gint tmp_toolbar_icon_size;
  GtkWidget *hbox1;
  GtkWidget *lFindNumber;
  GtkWidget *eFindName;
  GtkWidget *lFindDesignation;
  GtkWidget *eFindCity;
  GtkWidget *bSearch;
  GtkWidget *scrolledwindow1;
  GtkWidget *tree1;
  GtkWidget *notebook1;
  GtkWidget *fixed1;
  GtkWidget *eNumber;
  GtkWidget *eDesignation;
  GtkWidget *eDeliveredAt;
  GtkWidget *eAddressNumber;
  GtkWidget *tvAddress;
  GtkWidget *eOrderedAt;
  GtkWidget *lCustom;
  GtkWidget *lCustomNumber;
  GtkWidget *bSearchCustom;
  GtkWidget *lNumber;
  GtkWidget *lOrderedAt;
  GtkWidget *lDeliveredAt;
  GtkWidget *ePostage;
  GtkWidget *lDesignation;
  GtkWidget *ePacking;
  GtkWidget *label27;
  GtkWidget *label26;
  GtkWidget *eMiscCost;
  GtkWidget *label28;
  GtkWidget *label2;
  GtkWidget *fixed2;
  GtkWidget *eSupplyNumber;
  GtkWidget *tvSupply;
  GtkWidget *eSupplyDesignation;
  GtkWidget *label8;
  GtkWidget *label5;
  GtkWidget *bSearchSupply;
  GtkWidget *label1;
  GtkWidget *table2;
  GtkWidget *hbox5;
  GtkWidget *label6;
  GtkWidget *bSearchGets;
  GtkWidget *eGetsNumber;
  GtkWidget *vbox2;
  GtkWidget *hbox8;
  GtkWidget *label12;
  GtkWidget *eLoadReference;
  GtkWidget *hbox9;
  GtkWidget *label13;
  GtkWidget *ePickupAt;
  GtkWidget *hbox10;
  GtkWidget *label14;
  GtkWidget *eGetsRemarkPickup;
  GtkWidget *hbox2;
  GtkWidget *label11;
  GtkWidget *bSearchGetsPartner;
  GtkWidget *eGetsPartner;
  GtkWidget *vbox3;
  GtkWidget *hbox11;
  GtkWidget *label9;
  GtkWidget *eGetsDesignation;
  GtkWidget *hbox12;
  GtkWidget *label15;
  GtkWidget *eNumber;
  GtkWidget *vbox4;
  GtkWidget *hbox13;
  GtkWidget *label16;
  GtkWidget *bSearchForwardingAgency;
  GtkWidget *eForwardingAgency;
  GtkWidget *scrolledwindow5;
  GtkWidget *tvForwardingAgency;
  GtkWidget *vbox5;
  GtkWidget *hbox14;
  GtkWidget *label17;
  GtkWidget *bContactPerson;
  GtkWidget *eContactPerson;
  GtkWidget *scrolledwindow6;
  GtkWidget *tvContactPerson;
  GtkWidget *scrolledwindow4;
  GtkWidget *tvGets;
  GtkWidget *scrolledwindow3;
  GtkWidget *tvGetsPartner;
  GtkWidget *vbox6;
  GtkWidget *label20;
  GtkWidget *hbox16;
  GtkWidget *label19;
  GtkWidget *ePickupNoteNumber;
  GtkWidget *hbox15;
  GtkWidget *label18;
  GtkWidget *ePickupNoteDate;
  GtkWidget *hbox17;
  GtkWidget *label21;
  GtkWidget *combo1;
  GList *combo1_items = NULL;
  GtkWidget *cbPickupNoteStatus;
  GtkWidget *label3;
  GtkWidget *table1;
  GtkWidget *lPositionDesignation;
  GtkWidget *ePositionDesignation;
  GtkWidget *label7;
  GtkWidget *eAmount;
  GtkWidget *lPosition;
  GtkWidget *ePosition;
  GtkWidget *label10;
  GtkWidget *ePrice;
  GtkWidget *scrolledwindow2;
  GtkWidget *tvArticle;
  GtkWidget *vbox7;
  GtkWidget *lArticlesNumber;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *vbox8;
  GtkWidget *eArticleID;
  GtkWidget *eOrderPositionsUnit;
  GtkWidget *eOrderPositionsWrapping;
  GtkWidget *eOrderPositionAmountPerWrap;
  GtkWidget *vbox9;
  GtkWidget *bArticleSearch;
  GtkWidget *label25;
  GtkWidget *eOrderPositionsTaxVat;
  GtkWidget *label4;

  OrderMainwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (OrderMainwindow, 0, 0);
  gtk_window_set_title (GTK_WINDOW (OrderMainwindow), _("Order"));

  vbox1 = gtk_vbox_new (FALSE, 17);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (OrderMainwindow), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);
  gnome_app_fill_menu (GTK_MENU_SHELL (menubar1), menubar1_uiinfo,
                       NULL, FALSE, 0);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  hbox1 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, FALSE, 0);

  lFindNumber = gtk_label_new (_("Number"));
  gtk_widget_show (lFindNumber);
  gtk_box_pack_start (GTK_BOX (hbox1), lFindNumber, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (lFindNumber), GTK_JUSTIFY_CENTER);

  eFindName = gtk_entry_new ();
  gtk_widget_show (eFindName);
  gtk_box_pack_start (GTK_BOX (hbox1), eFindName, FALSE, FALSE, 0);

  lFindDesignation = gtk_label_new (_("Designation"));
  gtk_widget_show (lFindDesignation);
  gtk_box_pack_start (GTK_BOX (hbox1), lFindDesignation, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (lFindDesignation), GTK_JUSTIFY_CENTER);

  eFindCity = gtk_entry_new ();
  gtk_widget_show (eFindCity);
  gtk_box_pack_start (GTK_BOX (hbox1), eFindCity, FALSE, FALSE, 0);

  bSearch = gtk_button_new_with_mnemonic (_("Search"));
  gtk_widget_show (bSearch);
  gtk_box_pack_start (GTK_BOX (hbox1), bSearch, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow1, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (scrolledwindow1, GTK_CAN_FOCUS);

  tree1 = gtk_tree_view_new ();
  gtk_widget_show (tree1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), tree1);
  gtk_widget_set_size_request (tree1, -1, 106);
  gtk_container_set_border_width (GTK_CONTAINER (tree1), 5);
  GTK_WIDGET_UNSET_FLAGS (tree1, GTK_CAN_FOCUS);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox1), notebook1, TRUE, TRUE, 0);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed1);

  eNumber = gtk_entry_new ();
  gtk_widget_show (eNumber);
  gtk_fixed_put (GTK_FIXED (fixed1), eNumber, 120, 8);
  gtk_widget_set_size_request (eNumber, 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (eNumber), 20);

  eDesignation = gtk_entry_new ();
  gtk_widget_show (eDesignation);
  gtk_fixed_put (GTK_FIXED (fixed1), eDesignation, 528, 8);
  gtk_widget_set_size_request (eDesignation, 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (eDesignation), 50);

  eDeliveredAt = gtk_entry_new ();
  gtk_widget_show (eDeliveredAt);
  gtk_fixed_put (GTK_FIXED (fixed1), eDeliveredAt, 120, 72);
  gtk_widget_set_size_request (eDeliveredAt, 0, 0);

  eAddressNumber = gtk_entry_new ();
  gtk_widget_show (eAddressNumber);
  gtk_fixed_put (GTK_FIXED (fixed1), eAddressNumber, 384, 144);
  gtk_widget_set_size_request (eAddressNumber, 0, 0);

  tvAddress = gtk_text_view_new ();
  gtk_widget_show (tvAddress);
  gtk_fixed_put (GTK_FIXED (fixed1), tvAddress, 136, 200);
  gtk_widget_set_size_request (tvAddress, 344, 184);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (tvAddress), FALSE);

  eOrderedAt = gtk_entry_new ();
  gtk_widget_show (eOrderedAt);
  gtk_fixed_put (GTK_FIXED (fixed1), eOrderedAt, 120, 40);
  gtk_widget_set_size_request (eOrderedAt, 0, 0);

  lCustom = gtk_label_new (_("Customer"));
  gtk_widget_show (lCustom);
  gtk_fixed_put (GTK_FIXED (fixed1), lCustom, 24, 200);
  gtk_widget_set_size_request (lCustom, 0, 0);

  lCustomNumber = gtk_label_new (_("Custom-Number"));
  gtk_widget_show (lCustomNumber);
  gtk_fixed_put (GTK_FIXED (fixed1), lCustomNumber, 208, 144);
  gtk_widget_set_size_request (lCustomNumber, 0, 0);

  bSearchCustom = gtk_button_new_with_mnemonic (_("search address ..."));
  gtk_widget_show (bSearchCustom);
  gtk_fixed_put (GTK_FIXED (fixed1), bSearchCustom, 16, 136);
  gtk_widget_set_size_request (bSearchCustom, 0, 0);

  lNumber = gtk_label_new (_("Number"));
  gtk_widget_show (lNumber);
  gtk_fixed_put (GTK_FIXED (fixed1), lNumber, 0, 8);
  gtk_widget_set_size_request (lNumber, 0, 0);

  lOrderedAt = gtk_label_new (_("ordered at"));
  gtk_widget_show (lOrderedAt);
  gtk_fixed_put (GTK_FIXED (fixed1), lOrderedAt, 0, 40);
  gtk_widget_set_size_request (lOrderedAt, 0, 0);
  gtk_label_set_justify (GTK_LABEL (lOrderedAt), GTK_JUSTIFY_CENTER);

  lDeliveredAt = gtk_label_new (_("delivered at"));
  gtk_widget_show (lDeliveredAt);
  gtk_fixed_put (GTK_FIXED (fixed1), lDeliveredAt, 0, 72);
  gtk_widget_set_size_request (lDeliveredAt, 0, 0);
  gtk_label_set_justify (GTK_LABEL (lDeliveredAt), GTK_JUSTIFY_CENTER);

  ePostage = gtk_entry_new ();
  gtk_widget_show (ePostage);
  gtk_fixed_put (GTK_FIXED (fixed1), ePostage, 816, 208);
  gtk_widget_set_size_request (ePostage, 158, 31);

  lDesignation = gtk_label_new (_("Desig."));
  gtk_widget_show (lDesignation);
  gtk_fixed_put (GTK_FIXED (fixed1), lDesignation, 376, 8);
  gtk_widget_set_size_request (lDesignation, 0, 0);
  gtk_label_set_justify (GTK_LABEL (lDesignation), GTK_JUSTIFY_CENTER);

  ePacking = gtk_entry_new ();
  gtk_widget_show (ePacking);
  gtk_fixed_put (GTK_FIXED (fixed1), ePacking, 816, 168);
  gtk_widget_set_size_request (ePacking, 158, 31);

  label27 = gtk_label_new (_("Packing\n"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed1), label27, 592, 176);
  gtk_widget_set_size_request (label27, 0, 0);

  label26 = gtk_label_new (_("Truckage/Postage"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed1), label26, 592, 208);
  gtk_widget_set_size_request (label26, 0, 0);

  eMiscCost = gtk_entry_new ();
  gtk_widget_show (eMiscCost);
  gtk_fixed_put (GTK_FIXED (fixed1), eMiscCost, 816, 248);
  gtk_widget_set_size_request (eMiscCost, 158, 31);

  label28 = gtk_label_new (_("Misc. cost"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed1), label28, 592, 248);
  gtk_widget_set_size_request (label28, 0, 0);

  label2 = gtk_label_new (_("Order"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label2);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  eSupplyNumber = gtk_entry_new ();
  gtk_widget_show (eSupplyNumber);
  gtk_fixed_put (GTK_FIXED (fixed2), eSupplyNumber, 336, 88);
  gtk_widget_set_size_request (eSupplyNumber, 158, 31);

  tvSupply = gtk_text_view_new ();
  gtk_widget_show (tvSupply);
  gtk_fixed_put (GTK_FIXED (fixed2), tvSupply, 16, 144);
  gtk_widget_set_size_request (tvSupply, 600, 224);

  eSupplyDesignation = gtk_entry_new ();
  gtk_widget_show (eSupplyDesignation);
  gtk_fixed_put (GTK_FIXED (fixed2), eSupplyDesignation, 144, 16);
  gtk_widget_set_size_request (eSupplyDesignation, 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (eSupplyDesignation), 50);

  label8 = gtk_label_new (_("Designation"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 16, 16);
  gtk_widget_set_size_request (label8, 0, 0);

  label5 = gtk_label_new (_("Supply to"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed2), label5, 232, 96);
  gtk_widget_set_size_request (label5, 0, 0);

  bSearchSupply = gtk_button_new_with_mnemonic (_("search address"));
  gtk_widget_show (bSearchSupply);
  gtk_fixed_put (GTK_FIXED (fixed2), bSearchSupply, 8, 88);
  gtk_widget_set_size_request (bSearchSupply, 0, 0);

  label1 = gtk_label_new (_("Supply"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label1);

  table2 = gtk_table_new (5, 3, FALSE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (notebook1), table2);
  gtk_widget_set_size_request (table2, 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table2), 2);
  gtk_table_set_row_spacings (GTK_TABLE (table2), 1);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 1);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox5);
  gtk_table_attach (GTK_TABLE (table2), hbox5, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_size_request (hbox5, 0, 0);

  label6 = gtk_label_new (_("gets from"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox5), label6, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label6, 0, 0);

  bSearchGets = gtk_button_new_with_mnemonic (_("search address ..."));
  gtk_widget_show (bSearchGets);
  gtk_box_pack_start (GTK_BOX (hbox5), bSearchGets, FALSE, FALSE, 0);
  gtk_widget_set_size_request (bSearchGets, 0, 0);

  eGetsNumber = gtk_entry_new ();
  gtk_widget_show (eGetsNumber);
  gtk_box_pack_start (GTK_BOX (hbox5), eGetsNumber, TRUE, TRUE, 0);
  gtk_widget_set_size_request (eGetsNumber, 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (eGetsNumber), 10);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_table_attach (GTK_TABLE (table2), vbox2, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hbox8 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox8, FALSE, FALSE, 0);

  label12 = gtk_label_new (_("Load reference"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox8), label12, TRUE, TRUE, 0);

  eLoadReference = gtk_entry_new ();
  gtk_widget_show (eLoadReference);
  gtk_box_pack_start (GTK_BOX (hbox8), eLoadReference, TRUE, TRUE, 0);

  hbox9 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox9, FALSE, FALSE, 0);

  label13 = gtk_label_new (_("Pick up at"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox9), label13, FALSE, FALSE, 0);

  ePickupAt = gtk_entry_new ();
  gtk_widget_show (ePickupAt);
  gtk_box_pack_start (GTK_BOX (hbox9), ePickupAt, TRUE, TRUE, 0);

  hbox10 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox10);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox10, TRUE, TRUE, 0);

  label14 = gtk_label_new (_("Remark"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox10), label14, FALSE, FALSE, 0);

  eGetsRemarkPickup = gtk_entry_new ();
  gtk_widget_show (eGetsRemarkPickup);
  gtk_box_pack_start (GTK_BOX (hbox10), eGetsRemarkPickup, TRUE, TRUE, 0);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_table_attach (GTK_TABLE (table2), hbox2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_size_request (hbox2, 0, 0);

  label11 = gtk_label_new (_("Partner"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox2), label11, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label11, 0, 0);

  bSearchGetsPartner = gtk_button_new_with_mnemonic (_("search Partner"));
  gtk_widget_show (bSearchGetsPartner);
  gtk_box_pack_start (GTK_BOX (hbox2), bSearchGetsPartner, FALSE, FALSE, 0);
  gtk_widget_set_size_request (bSearchGetsPartner, 0, 0);

  eGetsPartner = gtk_entry_new ();
  gtk_widget_show (eGetsPartner);
  gtk_box_pack_start (GTK_BOX (hbox2), eGetsPartner, TRUE, TRUE, 0);
  gtk_widget_set_size_request (eGetsPartner, 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (eGetsPartner), 10);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_table_attach (GTK_TABLE (table2), vbox3, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hbox11 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox11, TRUE, TRUE, 0);

  label9 = gtk_label_new (_("Designation"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox11), label9, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label9, 0, 0);

  eGetsDesignation = gtk_entry_new ();
  gtk_widget_show (eGetsDesignation);
  gtk_box_pack_start (GTK_BOX (hbox11), eGetsDesignation, TRUE, TRUE, 0);
  gtk_widget_set_size_request (eGetsDesignation, 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (eGetsDesignation), 20);

  hbox12 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox12);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox12, TRUE, TRUE, 0);

  label15 = gtk_label_new (_("Number"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox12), label15, FALSE, FALSE, 0);

  eNumber = gtk_entry_new ();
  gtk_widget_show (eNumber);
  gtk_box_pack_start (GTK_BOX (hbox12), eNumber, TRUE, TRUE, 0);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_table_attach (GTK_TABLE (table2), vbox4, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  hbox13 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox13);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox13, FALSE, FALSE, 0);

  label16 = gtk_label_new (_("Forwarding Agency"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox13), label16, FALSE, FALSE, 0);

  bSearchForwardingAgency = gtk_button_new_with_mnemonic (_("search"));
  gtk_widget_show (bSearchForwardingAgency);
  gtk_box_pack_start (GTK_BOX (hbox13), bSearchForwardingAgency, FALSE, FALSE, 0);

  eForwardingAgency = gtk_entry_new ();
  gtk_widget_show (eForwardingAgency);
  gtk_box_pack_start (GTK_BOX (hbox13), eForwardingAgency, TRUE, TRUE, 0);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_box_pack_start (GTK_BOX (vbox4), scrolledwindow5, TRUE, TRUE, 0);
  gtk_widget_set_size_request (scrolledwindow5, 99, 100);

  tvForwardingAgency = gtk_text_view_new ();
  gtk_widget_show (tvForwardingAgency);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), tvForwardingAgency);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (tvForwardingAgency), FALSE);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_table_attach (GTK_TABLE (table2), vbox5, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hbox14 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox14);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox14, FALSE, FALSE, 0);

  label17 = gtk_label_new (_("Contact Person"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox14), label17, FALSE, FALSE, 0);

  bContactPerson = gtk_button_new_with_mnemonic (_("search"));
  gtk_widget_show (bContactPerson);
  gtk_box_pack_start (GTK_BOX (hbox14), bContactPerson, FALSE, FALSE, 0);

  eContactPerson = gtk_entry_new ();
  gtk_widget_show (eContactPerson);
  gtk_box_pack_start (GTK_BOX (hbox14), eContactPerson, TRUE, TRUE, 0);

  scrolledwindow6 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow6);
  gtk_box_pack_start (GTK_BOX (vbox5), scrolledwindow6, TRUE, TRUE, 0);
  gtk_widget_set_size_request (scrolledwindow6, 99, 100);

  tvContactPerson = gtk_text_view_new ();
  gtk_widget_show (tvContactPerson);
  gtk_container_add (GTK_CONTAINER (scrolledwindow6), tvContactPerson);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (tvContactPerson), FALSE);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_table_attach (GTK_TABLE (table2), scrolledwindow4, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_size_request (scrolledwindow4, 99, 100);

  tvGets = gtk_text_view_new ();
  gtk_widget_show (tvGets);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), tvGets);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (tvGets), FALSE);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_table_attach (GTK_TABLE (table2), scrolledwindow3, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  tvGetsPartner = gtk_text_view_new ();
  gtk_widget_show (tvGetsPartner);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), tvGetsPartner);
  gtk_widget_set_size_request (tvGetsPartner, -1, 60);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_table_attach (GTK_TABLE (table2), vbox6, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label20 = gtk_label_new (_("Pickup-Note"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (vbox6), label20, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label20, 0, 0);
  gtk_label_set_justify (GTK_LABEL (label20), GTK_JUSTIFY_CENTER);

  hbox16 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox16);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox16, TRUE, TRUE, 0);

  label19 = gtk_label_new (_("Pickup-Nr.:"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox16), label19, FALSE, FALSE, 0);

  ePickupNoteNumber = gtk_entry_new ();
  gtk_widget_show (ePickupNoteNumber);
  gtk_box_pack_start (GTK_BOX (hbox16), ePickupNoteNumber, TRUE, TRUE, 0);
  gtk_entry_set_max_length (GTK_ENTRY (ePickupNoteNumber), 10);
  gtk_entry_set_width_chars (GTK_ENTRY (ePickupNoteNumber), 10);

  hbox15 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox15);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox15, TRUE, TRUE, 0);

  label18 = gtk_label_new (_("Date"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox15), label18, FALSE, FALSE, 0);

  ePickupNoteDate = gtk_entry_new ();
  gtk_widget_show (ePickupNoteDate);
  gtk_box_pack_start (GTK_BOX (hbox15), ePickupNoteDate, TRUE, TRUE, 0);
  gtk_entry_set_max_length (GTK_ENTRY (ePickupNoteDate), 10);
  gtk_entry_set_width_chars (GTK_ENTRY (ePickupNoteDate), 10);

  hbox17 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox17);
  gtk_table_attach (GTK_TABLE (table2), hbox17, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label21 = gtk_label_new (_("Status"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox17), label21, FALSE, FALSE, 0);

  combo1 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo1)->popwin),
                     "GladeParentKey", combo1);
  gtk_widget_show (combo1);
  gtk_box_pack_start (GTK_BOX (hbox17), combo1, TRUE, TRUE, 0);
  combo1_items = g_list_append (combo1_items, (gpointer) _("in progress"));
  combo1_items = g_list_append (combo1_items, (gpointer) _("already done"));
  combo1_items = g_list_append (combo1_items, (gpointer) _("problems"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo1), combo1_items);
  g_list_free (combo1_items);

  cbPickupNoteStatus = GTK_COMBO (combo1)->entry;
  gtk_widget_show (cbPickupNoteStatus);
  gtk_entry_set_max_length (GTK_ENTRY (cbPickupNoteStatus), 10);
  gtk_entry_set_width_chars (GTK_ENTRY (cbPickupNoteStatus), 15);

  label3 = gtk_label_new (_("Gets"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label3);

  table1 = gtk_table_new (4, 4, FALSE);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (notebook1), table1);

  lPositionDesignation = gtk_label_new (_("Designation"));
  gtk_widget_show (lPositionDesignation);
  gtk_table_attach (GTK_TABLE (table1), lPositionDesignation, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lPositionDesignation), 0, 0.5);

  ePositionDesignation = gtk_entry_new ();
  gtk_widget_show (ePositionDesignation);
  gtk_table_attach (GTK_TABLE (table1), ePositionDesignation, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (ePositionDesignation), 25);

  label7 = gtk_label_new (_("amount"));
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (table1), label7, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label7), 0, 0.5);

  eAmount = gtk_entry_new ();
  gtk_widget_show (eAmount);
  gtk_table_attach (GTK_TABLE (table1), eAmount, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  lPosition = gtk_label_new (_("Pos."));
  gtk_widget_show (lPosition);
  gtk_table_attach (GTK_TABLE (table1), lPosition, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lPosition), 0, 0.5);

  ePosition = gtk_entry_new ();
  gtk_widget_show (ePosition);
  gtk_table_attach (GTK_TABLE (table1), ePosition, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (ePosition), 5);

  label10 = gtk_label_new (_("Price"));
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table1), label10, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label10), 0, 0.5);

  ePrice = gtk_entry_new ();
  gtk_widget_show (ePrice);
  gtk_table_attach (GTK_TABLE (table1), ePrice, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_table_attach (GTK_TABLE (table1), scrolledwindow2, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_size_request (scrolledwindow2, -1, 152);

  tvArticle = gtk_text_view_new ();
  gtk_widget_show (tvArticle);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), tvArticle);

  vbox7 = gtk_vbox_new (TRUE, 0);
  gtk_widget_show (vbox7);
  gtk_table_attach (GTK_TABLE (table1), vbox7, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  lArticlesNumber = gtk_label_new (_("articles-Number"));
  gtk_widget_show (lArticlesNumber);
  gtk_box_pack_start (GTK_BOX (vbox7), lArticlesNumber, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (lArticlesNumber), 0, 0.5);

  label22 = gtk_label_new (_("Unit"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (vbox7), label22, FALSE, FALSE, 0);

  label23 = gtk_label_new (_("Wrapping"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (vbox7), label23, FALSE, FALSE, 0);

  label24 = gtk_label_new (_("Quant. per Wrap."));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (vbox7), label24, FALSE, FALSE, 0);

  vbox8 = gtk_vbox_new (TRUE, 0);
  gtk_widget_show (vbox8);
  gtk_table_attach (GTK_TABLE (table1), vbox8, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  eArticleID = gtk_entry_new ();
  gtk_widget_show (eArticleID);
  gtk_box_pack_start (GTK_BOX (vbox8), eArticleID, FALSE, FALSE, 0);
  gtk_editable_set_editable (GTK_EDITABLE (eArticleID), FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (eArticleID), 25);

  eOrderPositionsUnit = gtk_entry_new ();
  gtk_widget_show (eOrderPositionsUnit);
  gtk_box_pack_start (GTK_BOX (vbox8), eOrderPositionsUnit, FALSE, FALSE, 0);
  gtk_editable_set_editable (GTK_EDITABLE (eOrderPositionsUnit), FALSE);

  eOrderPositionsWrapping = gtk_entry_new ();
  gtk_widget_show (eOrderPositionsWrapping);
  gtk_box_pack_start (GTK_BOX (vbox8), eOrderPositionsWrapping, FALSE, FALSE, 0);
  gtk_editable_set_editable (GTK_EDITABLE (eOrderPositionsWrapping), FALSE);

  eOrderPositionAmountPerWrap = gtk_entry_new ();
  gtk_widget_show (eOrderPositionAmountPerWrap);
  gtk_box_pack_start (GTK_BOX (vbox8), eOrderPositionAmountPerWrap, FALSE, FALSE, 0);
  gtk_editable_set_editable (GTK_EDITABLE (eOrderPositionAmountPerWrap), FALSE);

  vbox9 = gtk_vbox_new (TRUE, 0);
  gtk_widget_show (vbox9);
  gtk_table_attach (GTK_TABLE (table1), vbox9, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  bArticleSearch = gtk_button_new_with_mnemonic (_("search article"));
  gtk_widget_show (bArticleSearch);
  gtk_box_pack_start (GTK_BOX (vbox9), bArticleSearch, FALSE, FALSE, 0);

  label25 = gtk_label_new (_("Tax-Vat"));
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table1), label25, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  eOrderPositionsTaxVat = gtk_entry_new ();
  gtk_widget_show (eOrderPositionsTaxVat);
  gtk_table_attach (GTK_TABLE (table1), eOrderPositionsTaxVat, 3, 4, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label4 = gtk_label_new (_("Postions"));
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label4);

  g_signal_connect ((gpointer) bSearch, "clicked",
                    G_CALLBACK (on_bSearch_clicked),
                    NULL);
  g_signal_connect ((gpointer) notebook1, "switch_page",
                    G_CALLBACK (on_notebook1_switch_page),
                    NULL);
  g_signal_connect ((gpointer) eAddressNumber, "changed",
                    G_CALLBACK (on_eAddressNumber_changed),
                    NULL);
  g_signal_connect ((gpointer) bSearchCustom, "clicked",
                    G_CALLBACK (on_bSearchCustom_clicked),
                    NULL);
  g_signal_connect ((gpointer) eSupplyNumber, "changed",
                    G_CALLBACK (on_eSupplyNumber_changed),
                    NULL);
  g_signal_connect ((gpointer) bSearchSupply, "clicked",
                    G_CALLBACK (on_bSearchSupply_clicked),
                    NULL);
  g_signal_connect ((gpointer) bSearchGets, "clicked",
                    G_CALLBACK (on_bSearchGet_clicked),
                    NULL);
  g_signal_connect ((gpointer) eGetsNumber, "changed",
                    G_CALLBACK (on_eGetsNumber_changed),
                    NULL);
  g_signal_connect ((gpointer) bSearchGetsPartner, "clicked",
                    G_CALLBACK (on_bSearchGetsPartner_clicked),
                    NULL);
  g_signal_connect ((gpointer) eGetsPartner, "changed",
                    G_CALLBACK (on_eGetsPartner_changed),
                    NULL);
  g_signal_connect ((gpointer) bSearchForwardingAgency, "clicked",
                    G_CALLBACK (on_bSearchForwardingAgency_clicked),
                    NULL);
  g_signal_connect ((gpointer) eForwardingAgency, "changed",
                    G_CALLBACK (on_eForwardingAgency_changed),
                    NULL);
  g_signal_connect ((gpointer) bContactPerson, "clicked",
                    G_CALLBACK (on_bContactPerson_clicked),
                    NULL);
  g_signal_connect ((gpointer) eContactPerson, "changed",
                    G_CALLBACK (on_eContactPerson_changed),
                    NULL);
  g_signal_connect ((gpointer) eArticleID, "changed",
                    G_CALLBACK (on_eArticleID_changed),
                    NULL);
  g_signal_connect ((gpointer) bArticleSearch, "clicked",
                    G_CALLBACK (on_bArticleSearch_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (OrderMainwindow, OrderMainwindow, "OrderMainwindow");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, menubar1_uiinfo[0].widget, "file1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, file1_menu_uiinfo[0].widget, "print_setup1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, file1_menu_uiinfo[1].widget, "print1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, print1_menu_uiinfo[0].widget, "invoice1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, print1_menu_uiinfo[1].widget, "delivery_note1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, print1_menu_uiinfo[2].widget, "pickup_note1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, file1_menu_uiinfo[2].widget, "separator4");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, file1_menu_uiinfo[3].widget, "quit1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, menubar1_uiinfo[1].widget, "order1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, order1_menu_uiinfo[0].widget, "new1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, order1_menu_uiinfo[1].widget, "edit1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, order1_menu_uiinfo[2].widget, "separator7");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, order1_menu_uiinfo[3].widget, "save1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, order1_menu_uiinfo[4].widget, "separator1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, order1_menu_uiinfo[5].widget, "delete1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, menubar1_uiinfo[2].widget, "supply1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, supply1_menu_uiinfo[0].widget, "SupplyNew1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, supply1_menu_uiinfo[1].widget, "SupplyEdit1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, supply1_menu_uiinfo[2].widget, "separator9");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, supply1_menu_uiinfo[3].widget, "SupplySave1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, supply1_menu_uiinfo[4].widget, "separator10");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, supply1_menu_uiinfo[5].widget, "SupplyDelete1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, menubar1_uiinfo[3].widget, "gets1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, gets1_menu_uiinfo[0].widget, "GetsNew1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, gets1_menu_uiinfo[1].widget, "GetsEdit1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, gets1_menu_uiinfo[2].widget, "separator11");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, gets1_menu_uiinfo[3].widget, "GetsSave1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, gets1_menu_uiinfo[4].widget, "separator12");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, gets1_menu_uiinfo[5].widget, "GetsDelete1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, menubar1_uiinfo[4].widget, "position1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, position1_menu_uiinfo[0].widget, "PositionNew1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, position1_menu_uiinfo[1].widget, "PositionEdit1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, position1_menu_uiinfo[2].widget, "separator8");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, position1_menu_uiinfo[3].widget, "PositionSave1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, position1_menu_uiinfo[4].widget, "separator5");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, position1_menu_uiinfo[5].widget, "PositionPrint1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, position1_menu_uiinfo[6].widget, "separator6");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, position1_menu_uiinfo[7].widget, "PositionDelete1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, lFindNumber, "lFindNumber");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, eFindName, "eFindName");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, lFindDesignation, "lFindDesignation");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, eFindCity, "eFindCity");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, bSearch, "bSearch");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, tree1, "tree1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, eNumber, "eNumber");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, eDesignation, "eDesignation");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, eDeliveredAt, "eDeliveredAt");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, eAddressNumber, "eAddressNumber");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, tvAddress, "tvAddress");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, eOrderedAt, "eOrderedAt");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, lCustom, "lCustom");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, lCustomNumber, "lCustomNumber");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, bSearchCustom, "bSearchCustom");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, lNumber, "lNumber");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, lOrderedAt, "lOrderedAt");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, lDeliveredAt, "lDeliveredAt");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, ePostage, "ePostage");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, lDesignation, "lDesignation");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, ePacking, "ePacking");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label27, "label27");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label26, "label26");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, eMiscCost, "eMiscCost");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label28, "label28");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label2, "label2");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, eSupplyNumber, "eSupplyNumber");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, tvSupply, "tvSupply");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, eSupplyDesignation, "eSupplyDesignation");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label8, "label8");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label5, "label5");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, bSearchSupply, "bSearchSupply");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label1, "label1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, table2, "table2");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label6, "label6");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, bSearchGets, "bSearchGets");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, eGetsNumber, "eGetsNumber");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label12, "label12");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, eLoadReference, "eLoadReference");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label13, "label13");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, ePickupAt, "ePickupAt");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label14, "label14");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, eGetsRemarkPickup, "eGetsRemarkPickup");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label11, "label11");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, bSearchGetsPartner, "bSearchGetsPartner");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, eGetsPartner, "eGetsPartner");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label9, "label9");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, eGetsDesignation, "eGetsDesignation");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label15, "label15");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, eNumber, "eNumber");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label16, "label16");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, bSearchForwardingAgency, "bSearchForwardingAgency");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, eForwardingAgency, "eForwardingAgency");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, tvForwardingAgency, "tvForwardingAgency");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label17, "label17");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, bContactPerson, "bContactPerson");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, eContactPerson, "eContactPerson");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, scrolledwindow6, "scrolledwindow6");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, tvContactPerson, "tvContactPerson");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, tvGets, "tvGets");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, tvGetsPartner, "tvGetsPartner");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label20, "label20");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label19, "label19");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, ePickupNoteNumber, "ePickupNoteNumber");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label18, "label18");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, ePickupNoteDate, "ePickupNoteDate");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label21, "label21");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, combo1, "combo1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, cbPickupNoteStatus, "cbPickupNoteStatus");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label3, "label3");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, table1, "table1");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, lPositionDesignation, "lPositionDesignation");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, ePositionDesignation, "ePositionDesignation");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label7, "label7");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, eAmount, "eAmount");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, lPosition, "lPosition");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, ePosition, "ePosition");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label10, "label10");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, ePrice, "ePrice");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, tvArticle, "tvArticle");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, lArticlesNumber, "lArticlesNumber");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label22, "label22");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label23, "label23");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label24, "label24");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, eArticleID, "eArticleID");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, eOrderPositionsUnit, "eOrderPositionsUnit");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, eOrderPositionsWrapping, "eOrderPositionsWrapping");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, eOrderPositionAmountPerWrap, "eOrderPositionAmountPerWrap");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, bArticleSearch, "bArticleSearch");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label25, "label25");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, eOrderPositionsTaxVat, "eOrderPositionsTaxVat");
  GLADE_HOOKUP_OBJECT (OrderMainwindow, label4, "label4");

  return OrderMainwindow;
}

