/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Mainwindow (void)
{
  GtkWidget *Mainwindow;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *file1;
  GtkWidget *file1_menu;
  GtkWidget *quit1;
  GtkWidget *services1;
  GtkWidget *services1_menu;
  GtkWidget *database_tools1;
  GtkWidget *create_client1;
  GtkWidget *help1;
  GtkWidget *table4;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *radiobutton3;
  GtkWidget *radiobutton4;
  GtkWidget *radiobutton5;
  GtkWidget *radiobutton6;
  GtkWidget *radiobutton7;
  GtkWidget *radiobutton8;
  GtkWidget *radiobutton9;
  GtkWidget *radiobutton10;
  GtkWidget *radiobutton11;
  GtkWidget *radiobutton12;
  GtkWidget *radiobutton13;
  GSList *radiobutton13_group = NULL;
  GtkWidget *radiobutton14;
  GSList *radiobutton14_group = NULL;
  GtkWidget *radiobutton15;
  GSList *radiobutton15_group = NULL;
  GtkWidget *radiobutton16;
  GSList *radiobutton16_group = NULL;
  GtkWidget *radiobutton17;
  GSList *radiobutton17_group = NULL;
  GtkWidget *radiobutton18;
  GSList *radiobutton18_group = NULL;
  GtkWidget *radiobutton19;
  GSList *radiobutton19_group = NULL;
  GtkWidget *radiobutton20;
  GSList *radiobutton20_group = NULL;
  GtkWidget *radiobutton21;
  GSList *radiobutton21_group = NULL;
  GtkWidget *radiobutton22;
  GSList *radiobutton22_group = NULL;
  GtkWidget *radiobutton23;
  GSList *radiobutton23_group = NULL;
  GtkWidget *radiobutton24;
  GSList *radiobutton24_group = NULL;
  GtkWidget *radiobutton25;
  GSList *radiobutton25_group = NULL;
  GtkWidget *radiobutton26;
  GSList *radiobutton26_group = NULL;
  GtkWidget *radiobutton27;
  GSList *radiobutton27_group = NULL;
  GtkWidget *radiobutton28;
  GSList *radiobutton28_group = NULL;
  GtkWidget *radiobutton29;
  GSList *radiobutton29_group = NULL;
  GtkWidget *radiobutton30;
  GSList *radiobutton30_group = NULL;
  GtkWidget *radiobutton31;
  GSList *radiobutton31_group = NULL;
  GtkWidget *radiobutton32;
  GSList *radiobutton32_group = NULL;
  GtkWidget *radiobutton33;
  GSList *radiobutton33_group = NULL;
  GtkWidget *radiobutton34;
  GSList *radiobutton34_group = NULL;
  GtkWidget *radiobutton35;
  GSList *radiobutton35_group = NULL;
  GtkWidget *radiobutton36;
  GSList *radiobutton36_group = NULL;
  GtkWidget *radiobutton37;
  GSList *radiobutton37_group = NULL;
  GtkWidget *radiobutton38;
  GSList *radiobutton38_group = NULL;
  GtkWidget *radiobutton39;
  GSList *radiobutton39_group = NULL;
  GtkWidget *radiobutton40;
  GSList *radiobutton40_group = NULL;
  GtkWidget *radiobutton41;
  GSList *radiobutton41_group = NULL;
  GtkWidget *radiobutton42;
  GSList *radiobutton42_group = NULL;
  GtkWidget *notebook1;
  GtkWidget *table1;
  GtkWidget *label5;
  GtkWidget *ePortXmlrpc;
  GtkWidget *ePortSSH;
  GtkWidget *eHostIP;
  GtkWidget *label7;
  GtkWidget *label6;
  GtkWidget *label4;
  GtkWidget *label8;
  GtkWidget *eDescription;
  GtkWidget *hbox2;
  GtkWidget *rbFalse;
  GSList *rbFalse_group = NULL;
  GtkWidget *rbTrue;
  GtkWidget *label9;
  GtkWidget *eName;
  GtkWidget *label10;
  GtkWidget *eLocale;
  GtkWidget *label11;
  GtkWidget *eProtocol;
  GtkWidget *label1;
  GtkWidget *scrolledwindow1;
  GtkWidget *tv1;
  GtkWidget *hbox1;
  GtkWidget *bCancel;
  GtkWidget *bTest;
  GtkWidget *bSaveData;
  GtkWidget *bRestartServer;
  GtkWidget *bOK;

  Mainwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Mainwindow), _("CUON Installer"));

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (Mainwindow), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  file1 = gtk_menu_item_new_with_mnemonic (_("File"));
  gtk_widget_show (file1);
  gtk_container_add (GTK_CONTAINER (menubar1), file1);

  file1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file1), file1_menu);

  quit1 = gtk_menu_item_new_with_mnemonic (_("Quit"));
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (file1_menu), quit1);

  services1 = gtk_menu_item_new_with_mnemonic (_("Services"));
  gtk_widget_show (services1);
  gtk_container_add (GTK_CONTAINER (menubar1), services1);

  services1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (services1), services1_menu);

  database_tools1 = gtk_menu_item_new_with_mnemonic (_("Database Tools"));
  gtk_widget_show (database_tools1);
  gtk_container_add (GTK_CONTAINER (services1_menu), database_tools1);

  create_client1 = gtk_menu_item_new_with_mnemonic (_("Create Client"));
  gtk_widget_show (create_client1);
  gtk_container_add (GTK_CONTAINER (services1_menu), create_client1);

  help1 = gtk_menu_item_new_with_mnemonic (_("Help"));
  gtk_widget_show (help1);
  gtk_container_add (GTK_CONTAINER (menubar1), help1);

  table4 = gtk_table_new (7, 6, FALSE);
  gtk_widget_show (table4);
  gtk_box_pack_start (GTK_BOX (vbox1), table4, TRUE, TRUE, 0);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, "");
  gtk_widget_show (radiobutton1);
  gtk_table_attach (GTK_TABLE (table4), radiobutton1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton2, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton2, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton3 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton3, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton3, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  radiobutton4 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton4, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton4, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  radiobutton5 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton5, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton5, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  radiobutton6 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton6, 5, 6, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton6, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6));

  radiobutton7 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton7, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton7, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton7), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton7));

  radiobutton8 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton8, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton8, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton8), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton8));

  radiobutton9 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton9, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton9, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton9), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton9));

  radiobutton10 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton10, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton10, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton10), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton10));

  radiobutton11 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton11, 4, 5, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton11, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton11), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton11));

  radiobutton12 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton12, 5, 6, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton12, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton12), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton12));

  radiobutton13 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton13, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton13, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton13), radiobutton13_group);
  radiobutton13_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton13));

  radiobutton14 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton14, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton14, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton14), radiobutton14_group);
  radiobutton14_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton14));

  radiobutton15 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton15, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton15, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton15), radiobutton15_group);
  radiobutton15_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton15));

  radiobutton16 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton16, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton16, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton16), radiobutton16_group);
  radiobutton16_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton16));

  radiobutton17 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton17, 4, 5, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton17, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton17), radiobutton17_group);
  radiobutton17_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton17));

  radiobutton18 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton18, 5, 6, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton18, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton18), radiobutton18_group);
  radiobutton18_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton18));

  radiobutton19 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton19, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton19, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton19), radiobutton19_group);
  radiobutton19_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton19));

  radiobutton20 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton20, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton20, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton20), radiobutton20_group);
  radiobutton20_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton20));

  radiobutton21 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton21, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton21, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton21), radiobutton21_group);
  radiobutton21_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton21));

  radiobutton22 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton22, 3, 4, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton22, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton22), radiobutton22_group);
  radiobutton22_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton22));

  radiobutton23 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton23, 4, 5, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton23, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton23), radiobutton23_group);
  radiobutton23_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton23));

  radiobutton24 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton24, 5, 6, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton24, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton24), radiobutton24_group);
  radiobutton24_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton24));

  radiobutton25 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton25, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton25, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton25), radiobutton25_group);
  radiobutton25_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton25));

  radiobutton26 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton26, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton26, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton26), radiobutton26_group);
  radiobutton26_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton26));

  radiobutton27 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton27, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton27, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton27), radiobutton27_group);
  radiobutton27_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton27));

  radiobutton28 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton28, 3, 4, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton28, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton28), radiobutton28_group);
  radiobutton28_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton28));

  radiobutton29 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton29, 4, 5, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton29, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton29), radiobutton29_group);
  radiobutton29_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton29));

  radiobutton30 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton30, 5, 6, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton30, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton30), radiobutton30_group);
  radiobutton30_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton30));

  radiobutton31 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton31, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton31, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton31), radiobutton31_group);
  radiobutton31_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton31));

  radiobutton32 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton32, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton32, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton32), radiobutton32_group);
  radiobutton32_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton32));

  radiobutton33 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton33, 2, 3, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton33, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton33), radiobutton33_group);
  radiobutton33_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton33));

  radiobutton34 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton34, 3, 4, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton34, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton34), radiobutton34_group);
  radiobutton34_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton34));

  radiobutton35 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton35, 4, 5, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton35, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton35), radiobutton35_group);
  radiobutton35_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton35));

  radiobutton36 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton36, 5, 6, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton36, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton36), radiobutton36_group);
  radiobutton36_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton36));

  radiobutton37 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton37, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton37, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton37), radiobutton37_group);
  radiobutton37_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton37));

  radiobutton38 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton38, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton38, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton38), radiobutton38_group);
  radiobutton38_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton38));

  radiobutton39 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton39, 2, 3, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton39, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton39), radiobutton39_group);
  radiobutton39_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton39));

  radiobutton40 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton40, 3, 4, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton40, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton40), radiobutton40_group);
  radiobutton40_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton40));

  radiobutton41 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton41, 4, 5, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton41, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton41), radiobutton41_group);
  radiobutton41_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton41));

  radiobutton42 = gtk_radio_button_new (NULL);
  gtk_table_attach (GTK_TABLE (table4), radiobutton42, 5, 6, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (radiobutton42, GTK_CAN_FOCUS);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton42), radiobutton42_group);
  radiobutton42_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton42));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox1), notebook1, TRUE, TRUE, 0);

  table1 = gtk_table_new (6, 4, FALSE);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (notebook1), table1);

  label5 = gtk_label_new (_("Description"));
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table1), label5, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);

  ePortXmlrpc = gtk_entry_new ();
  gtk_widget_show (ePortXmlrpc);
  gtk_table_attach (GTK_TABLE (table1), ePortXmlrpc, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  ePortSSH = gtk_entry_new ();
  gtk_widget_show (ePortSSH);
  gtk_table_attach (GTK_TABLE (table1), ePortSSH, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  eHostIP = gtk_entry_new ();
  gtk_widget_show (eHostIP);
  gtk_table_attach (GTK_TABLE (table1), eHostIP, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label7 = gtk_label_new (_("Port-XMLRPC"));
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (table1), label7, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label7), 0, 0.5);

  label6 = gtk_label_new (_("Port-SSH"));
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table1), label6, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);

  label4 = gtk_label_new (_("Host-IP"));
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table1), label4, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);

  label8 = gtk_label_new (_("Name"));
  gtk_widget_show (label8);
  gtk_table_attach (GTK_TABLE (table1), label8, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label8), 0, 0.5);

  eDescription = gtk_entry_new ();
  gtk_widget_show (eDescription);
  gtk_table_attach (GTK_TABLE (table1), eDescription, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_table_attach (GTK_TABLE (table1), hbox2, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  rbFalse = gtk_radio_button_new_with_mnemonic (NULL, _("False"));
  gtk_widget_show (rbFalse);
  gtk_box_pack_start (GTK_BOX (hbox2), rbFalse, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbFalse), rbFalse_group);
  rbFalse_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbFalse));

  rbTrue = gtk_radio_button_new_with_mnemonic (NULL, _("True"));
  gtk_widget_show (rbTrue);
  gtk_box_pack_start (GTK_BOX (hbox2), rbTrue, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbTrue), rbFalse_group);
  rbFalse_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbTrue));

  label9 = gtk_label_new (_("Default"));
  gtk_widget_show (label9);
  gtk_table_attach (GTK_TABLE (table1), label9, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label9), 0, 0.5);

  eName = gtk_entry_new ();
  gtk_widget_show (eName);
  gtk_table_attach (GTK_TABLE (table1), eName, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label10 = gtk_label_new (_("locale"));
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table1), label10, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label10), 0, 0.5);

  eLocale = gtk_entry_new ();
  gtk_widget_show (eLocale);
  gtk_table_attach (GTK_TABLE (table1), eLocale, 3, 4, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label11 = gtk_label_new (_("Protocol"));
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (table1), label11, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label11), 0, 0.5);

  eProtocol = gtk_entry_new ();
  gtk_widget_show (eProtocol);
  gtk_table_attach (GTK_TABLE (table1), eProtocol, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label1 = gtk_label_new (_("Server"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  tv1 = gtk_text_view_new ();
  gtk_widget_show (tv1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), tv1);
  gtk_widget_set_size_request (tv1, 590, 160);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (tv1), FALSE);

  hbox1 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  bCancel = gtk_button_new_with_mnemonic (_("Cancel"));
  gtk_widget_show (bCancel);
  gtk_box_pack_start (GTK_BOX (hbox1), bCancel, FALSE, FALSE, 0);

  bTest = gtk_button_new_with_mnemonic (_("Test"));
  gtk_widget_show (bTest);
  gtk_box_pack_start (GTK_BOX (hbox1), bTest, FALSE, FALSE, 0);

  bSaveData = gtk_button_new_with_mnemonic (_("Save Data"));
  gtk_widget_show (bSaveData);
  gtk_box_pack_start (GTK_BOX (hbox1), bSaveData, FALSE, FALSE, 0);

  bRestartServer = gtk_button_new_with_mnemonic (_("restart server"));
  gtk_widget_show (bRestartServer);
  gtk_box_pack_start (GTK_BOX (hbox1), bRestartServer, FALSE, FALSE, 0);

  bOK = gtk_button_new_with_mnemonic (_("Start Install"));
  gtk_widget_show (bOK);
  gtk_box_pack_start (GTK_BOX (hbox1), bOK, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) database_tools1, "activate",
                    G_CALLBACK (on_database_tools1_activate),
                    NULL);
  g_signal_connect ((gpointer) create_client1, "activate",
                    G_CALLBACK (on_create_client1_activate),
                    NULL);
  g_signal_connect ((gpointer) help1, "activate",
                    G_CALLBACK (on_help1_activate),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton4, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton5, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton6, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton7, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton8, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton9, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton10, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton11, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton12, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton13, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton14, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton15, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton16, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton17, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton18, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton19, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton20, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton21, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton22, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton23, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton24, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton25, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton26, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton27, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton28, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton29, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton30, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton31, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton32, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton33, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton34, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton35, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton36, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton37, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton38, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton39, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton40, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton41, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton42, "toggled",
                    G_CALLBACK (on_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) bSaveData, "clicked",
                    G_CALLBACK (on_bSaveData_clicked),
                    NULL);
  g_signal_connect ((gpointer) bRestartServer, "clicked",
                    G_CALLBACK (on_bRestartServer_clicked),
                    NULL);
  g_signal_connect ((gpointer) bOK, "clicked",
                    G_CALLBACK (on_bOK_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Mainwindow, Mainwindow, "Mainwindow");
  GLADE_HOOKUP_OBJECT (Mainwindow, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (Mainwindow, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (Mainwindow, file1, "file1");
  GLADE_HOOKUP_OBJECT (Mainwindow, file1_menu, "file1_menu");
  GLADE_HOOKUP_OBJECT (Mainwindow, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (Mainwindow, services1, "services1");
  GLADE_HOOKUP_OBJECT (Mainwindow, services1_menu, "services1_menu");
  GLADE_HOOKUP_OBJECT (Mainwindow, database_tools1, "database_tools1");
  GLADE_HOOKUP_OBJECT (Mainwindow, create_client1, "create_client1");
  GLADE_HOOKUP_OBJECT (Mainwindow, help1, "help1");
  GLADE_HOOKUP_OBJECT (Mainwindow, table4, "table4");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton6, "radiobutton6");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton7, "radiobutton7");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton8, "radiobutton8");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton9, "radiobutton9");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton10, "radiobutton10");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton11, "radiobutton11");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton12, "radiobutton12");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton13, "radiobutton13");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton14, "radiobutton14");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton15, "radiobutton15");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton16, "radiobutton16");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton17, "radiobutton17");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton18, "radiobutton18");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton19, "radiobutton19");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton20, "radiobutton20");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton21, "radiobutton21");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton22, "radiobutton22");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton23, "radiobutton23");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton24, "radiobutton24");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton25, "radiobutton25");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton26, "radiobutton26");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton27, "radiobutton27");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton28, "radiobutton28");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton29, "radiobutton29");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton30, "radiobutton30");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton31, "radiobutton31");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton32, "radiobutton32");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton33, "radiobutton33");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton34, "radiobutton34");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton35, "radiobutton35");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton36, "radiobutton36");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton37, "radiobutton37");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton38, "radiobutton38");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton39, "radiobutton39");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton40, "radiobutton40");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton41, "radiobutton41");
  GLADE_HOOKUP_OBJECT (Mainwindow, radiobutton42, "radiobutton42");
  GLADE_HOOKUP_OBJECT (Mainwindow, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (Mainwindow, table1, "table1");
  GLADE_HOOKUP_OBJECT (Mainwindow, label5, "label5");
  GLADE_HOOKUP_OBJECT (Mainwindow, ePortXmlrpc, "ePortXmlrpc");
  GLADE_HOOKUP_OBJECT (Mainwindow, ePortSSH, "ePortSSH");
  GLADE_HOOKUP_OBJECT (Mainwindow, eHostIP, "eHostIP");
  GLADE_HOOKUP_OBJECT (Mainwindow, label7, "label7");
  GLADE_HOOKUP_OBJECT (Mainwindow, label6, "label6");
  GLADE_HOOKUP_OBJECT (Mainwindow, label4, "label4");
  GLADE_HOOKUP_OBJECT (Mainwindow, label8, "label8");
  GLADE_HOOKUP_OBJECT (Mainwindow, eDescription, "eDescription");
  GLADE_HOOKUP_OBJECT (Mainwindow, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Mainwindow, rbFalse, "rbFalse");
  GLADE_HOOKUP_OBJECT (Mainwindow, rbTrue, "rbTrue");
  GLADE_HOOKUP_OBJECT (Mainwindow, label9, "label9");
  GLADE_HOOKUP_OBJECT (Mainwindow, eName, "eName");
  GLADE_HOOKUP_OBJECT (Mainwindow, label10, "label10");
  GLADE_HOOKUP_OBJECT (Mainwindow, eLocale, "eLocale");
  GLADE_HOOKUP_OBJECT (Mainwindow, label11, "label11");
  GLADE_HOOKUP_OBJECT (Mainwindow, eProtocol, "eProtocol");
  GLADE_HOOKUP_OBJECT (Mainwindow, label1, "label1");
  GLADE_HOOKUP_OBJECT (Mainwindow, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (Mainwindow, tv1, "tv1");
  GLADE_HOOKUP_OBJECT (Mainwindow, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Mainwindow, bCancel, "bCancel");
  GLADE_HOOKUP_OBJECT (Mainwindow, bTest, "bTest");
  GLADE_HOOKUP_OBJECT (Mainwindow, bSaveData, "bSaveData");
  GLADE_HOOKUP_OBJECT (Mainwindow, bRestartServer, "bRestartServer");
  GLADE_HOOKUP_OBJECT (Mainwindow, bOK, "bOK");

  return Mainwindow;
}

