/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_SqlProgressBar (void)
{
  GtkWidget *SqlProgressBar;
  GtkWidget *vbox1;
  GtkWidget *label1;
  GtkWidget *progressbar1;
  GtkWidget *label2;

  SqlProgressBar = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (SqlProgressBar, 392, -1);
  gtk_window_set_title (GTK_WINDOW (SqlProgressBar), _("Load Sql-Definitions from Server"));
  gtk_window_set_position (GTK_WINDOW (SqlProgressBar), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (SqlProgressBar), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (SqlProgressBar), FALSE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (SqlProgressBar), vbox1);

  label1 = gtk_label_new ("");
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (vbox1), label1, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_LEFT);

  progressbar1 = gtk_progress_bar_new ();
  gtk_widget_show (progressbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), progressbar1, FALSE, TRUE, 0);
  gtk_progress_bar_set_pulse_step (GTK_PROGRESS_BAR (progressbar1), 0.05);
  gtk_progress_bar_set_text (GTK_PROGRESS_BAR (progressbar1), _("load SQL-Definition"));

  label2 = gtk_label_new ("");
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (vbox1), label2, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_LEFT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (SqlProgressBar, SqlProgressBar, "SqlProgressBar");
  GLADE_HOOKUP_OBJECT (SqlProgressBar, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (SqlProgressBar, label1, "label1");
  GLADE_HOOKUP_OBJECT (SqlProgressBar, progressbar1, "progressbar1");
  GLADE_HOOKUP_OBJECT (SqlProgressBar, label2, "label2");

  return SqlProgressBar;
}

