/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

static GnomeUIInfo connect1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Login"),
    NULL,
    (gpointer) on_login1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Logout"),
    NULL,
    (gpointer) NULL, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("quit"),
    N_("Close the Application"),
    (gpointer) on_end1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-quit",
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo data_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("_Addresses"),
    NULL,
    (gpointer) on_addresses1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Arti_cles"),
    NULL,
    (gpointer) on_articles1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo action1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("_Order"),
    NULL,
    (gpointer) on_order1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Stock"),
    NULL,
    (gpointer) on_stock1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo tools1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Preferences"),
    NULL,
    (gpointer) on_preferences1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Update"),
    NULL,
    (gpointer) on_update1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Report-Generator"),
    NULL,
    (gpointer) on_report_generator1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo help1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("About"),
    NULL,
    (gpointer) on_about1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo menubar1_uiinfo[] =
{
  {
    GNOME_APP_UI_SUBTREE, N_("Connect"),
    NULL,
    connect1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Data"),
    NULL,
    data_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Action"),
    NULL,
    action1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Tools"),
    NULL,
    tools1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Help"),
    NULL,
    help1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *table1;
  GtkWidget *label1;
  GtkWidget *eUserName;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("C U O N"));
  gtk_window_set_default_size (GTK_WINDOW (window1), 662, 142);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window1), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);
  gnome_app_fill_menu (GTK_MENU_SHELL (menubar1), menubar1_uiinfo,
                       NULL, FALSE, 0);

  table1 = gtk_table_new (3, 4, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox1), table1, TRUE, TRUE, 0);

  label1 = gtk_label_new (_("User"));
  gtk_widget_show (label1);
  gtk_table_attach (GTK_TABLE (table1), label1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label1), 0, 0.5);

  eUserName = gtk_entry_new ();
  gtk_widget_show (eUserName);
  gtk_table_attach (GTK_TABLE (table1), eUserName, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (eUserName), FALSE);

  g_signal_connect ((gpointer) eUserName, "changed",
                    G_CALLBACK (on_eUserName_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window1, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (window1, menubar1_uiinfo[0].widget, "connect1");
  GLADE_HOOKUP_OBJECT (window1, connect1_menu_uiinfo[0].widget, "login1");
  GLADE_HOOKUP_OBJECT (window1, connect1_menu_uiinfo[1].widget, "logout1");
  GLADE_HOOKUP_OBJECT (window1, connect1_menu_uiinfo[2].widget, "trennlinie1");
  GLADE_HOOKUP_OBJECT (window1, connect1_menu_uiinfo[3].widget, "end1");
  GLADE_HOOKUP_OBJECT (window1, menubar1_uiinfo[1].widget, "data");
  GLADE_HOOKUP_OBJECT (window1, data_menu_uiinfo[0].widget, "addresses1");
  GLADE_HOOKUP_OBJECT (window1, data_menu_uiinfo[1].widget, "articles1");
  GLADE_HOOKUP_OBJECT (window1, menubar1_uiinfo[2].widget, "action1");
  GLADE_HOOKUP_OBJECT (window1, action1_menu_uiinfo[0].widget, "order1");
  GLADE_HOOKUP_OBJECT (window1, action1_menu_uiinfo[1].widget, "stock1");
  GLADE_HOOKUP_OBJECT (window1, menubar1_uiinfo[3].widget, "tools1");
  GLADE_HOOKUP_OBJECT (window1, tools1_menu_uiinfo[0].widget, "preferences1");
  GLADE_HOOKUP_OBJECT (window1, tools1_menu_uiinfo[1].widget, "update1");
  GLADE_HOOKUP_OBJECT (window1, tools1_menu_uiinfo[2].widget, "report_generator1");
  GLADE_HOOKUP_OBJECT (window1, menubar1_uiinfo[4].widget, "help1");
  GLADE_HOOKUP_OBJECT (window1, help1_menu_uiinfo[0].widget, "about1");
  GLADE_HOOKUP_OBJECT (window1, table1, "table1");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, eUserName, "eUserName");

  return window1;
}

