/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("window1");
gchar *s = N_("_File");
gchar *s = N_("_Edit");
gchar *s = N_("_View");
gchar *s = N_("_Help");
gchar *s = N_("_About");
gchar *s = N_("Username");
gchar *s = N_("Lastname");
gchar *s = N_("Firstname");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("User");
